/*
 * Color Time Pass
 * Copyright (C) 2016 Appgramming. All rights reserved.
 * http://www.appgramming.com
 */
package com.appgramming.colortimepass.helpers;

import java.util.LinkedHashMap;

/**
 * A static class to map color codes to CSS color names.
 */
public class NamedColors {

    /**
     * Mask used to remove the alpha component from a RGB color.
     */
    private static final int NO_ALPHA_MASK = 0xFFFFFF;

    /**
     * A static hash map that contains color int value -> name mappings.
     */
    private static final LinkedHashMap<Integer, String> sNamedColorsMap;

    static {
        // Create and fill the color name hash map
        sNamedColorsMap = new LinkedHashMap<>();
        sNamedColorsMap.put(0x4C4F56, "Abbey");
        sNamedColorsMap.put(0x1B1404, "Acadia");
        sNamedColorsMap.put(0x7CB0A1, "Acapulco");
        sNamedColorsMap.put(0xC9FFE5, "Aero Blue");
        sNamedColorsMap.put(0x714693, "Affair");
        sNamedColorsMap.put(0xD4C4A8, "Akaroa");
        sNamedColorsMap.put(0xFAFAFA, "Alabaster");
        sNamedColorsMap.put(0xF5E9D3, "Albescent White");
        sNamedColorsMap.put(0x93DFB8, "Algae Green");
        sNamedColorsMap.put(0xF0F8FF, "Alice Blue");
        sNamedColorsMap.put(0xE32636, "Alizarin Crimson");
        sNamedColorsMap.put(0x0076A3, "Allports");
        sNamedColorsMap.put(0xEED9C4, "Almond");
        sNamedColorsMap.put(0x907B71, "Almond Frost");
        sNamedColorsMap.put(0xAF8F2C, "Alpine");
        sNamedColorsMap.put(0xDBDBDB, "Alto");
        sNamedColorsMap.put(0xA9ACB6, "Aluminium");
        sNamedColorsMap.put(0xE52B50, "Amaranth");
        sNamedColorsMap.put(0x3B7A57, "Amazon");
        sNamedColorsMap.put(0xFFBF00, "Amber");
        sNamedColorsMap.put(0x87756E, "Americano");
        sNamedColorsMap.put(0x9966CC, "Amethyst");
        sNamedColorsMap.put(0xA397B4, "Amethyst Smoke");
        sNamedColorsMap.put(0xF9EAF3, "Amour");
        sNamedColorsMap.put(0x7B9F80, "Amulet");
        sNamedColorsMap.put(0x9DE5FF, "Anakiwa");
        sNamedColorsMap.put(0xC88A65, "Antique Brass");
        sNamedColorsMap.put(0x704A07, "Antique Bronze");
        sNamedColorsMap.put(0xE0B646, "Anzac");
        sNamedColorsMap.put(0xDFBE6F, "Apache");
        sNamedColorsMap.put(0x4FA83D, "Apple");
        sNamedColorsMap.put(0xAF4D43, "Apple Blossom");
        sNamedColorsMap.put(0xE2F3EC, "Apple Green");
        sNamedColorsMap.put(0xEB9373, "Apricot");
        sNamedColorsMap.put(0xFBCEB1, "Apricot Peach");
        sNamedColorsMap.put(0xFFFEEC, "Apricot White");
        sNamedColorsMap.put(0x014B43, "Aqua Deep");
        sNamedColorsMap.put(0x5FA777, "Aqua Forest");
        sNamedColorsMap.put(0xEDF5F5, "Aqua Haze");
        sNamedColorsMap.put(0xA1DAD7, "Aqua Island");
        sNamedColorsMap.put(0xEAF9F5, "Aqua Spring");
        sNamedColorsMap.put(0xE8F5F2, "Aqua Squeeze");
        sNamedColorsMap.put(0x7FFFD4, "Aquamarine");
        sNamedColorsMap.put(0x71D9E2, "Aquamarine Blue");
        sNamedColorsMap.put(0x110C6C, "Arapawa");
        sNamedColorsMap.put(0x433E37, "Armadillo");
        sNamedColorsMap.put(0x948771, "Arrowtown");
        sNamedColorsMap.put(0xC6C3B5, "Ash");
        sNamedColorsMap.put(0x7BA05B, "Asparagus");
        sNamedColorsMap.put(0x130A06, "Asphalt");
        sNamedColorsMap.put(0xFAEAB9, "Astra");
        sNamedColorsMap.put(0x327DA0, "Astral");
        sNamedColorsMap.put(0x283A77, "Astronaut");
        sNamedColorsMap.put(0x013E62, "Astronaut Blue");
        sNamedColorsMap.put(0xEEF0F3, "Athens Gray");
        sNamedColorsMap.put(0xECEBCE, "Aths Special");
        sNamedColorsMap.put(0x97CD2D, "Atlantis");
        sNamedColorsMap.put(0x0A6F75, "Atoll");
        sNamedColorsMap.put(0xFF9966, "Atomic Tangerine");
        sNamedColorsMap.put(0x97605D, "Au Chico");
        sNamedColorsMap.put(0x3B0910, "Aubergine");
        sNamedColorsMap.put(0xF5FFBE, "Australian Mint");
        sNamedColorsMap.put(0x888D65, "Avocado");
        sNamedColorsMap.put(0x4E6649, "Axolotl");
        sNamedColorsMap.put(0xF7C8DA, "Azalea");
        sNamedColorsMap.put(0x0D1C19, "Aztec");
        sNamedColorsMap.put(0x315BA1, "Azure");
        sNamedColorsMap.put(0x007FFF, "Azure Radiance");
        sNamedColorsMap.put(0xE0FFFF, "Baby Blue");
        sNamedColorsMap.put(0x026395, "Bahama Blue");
        sNamedColorsMap.put(0xA5CB0C, "Bahia");
        sNamedColorsMap.put(0xFFF8D1, "Baja White");
        sNamedColorsMap.put(0x859FAF, "Bali Hai");
        sNamedColorsMap.put(0x2A2630, "Baltic Sea");
        sNamedColorsMap.put(0xDA6304, "Bamboo");
        sNamedColorsMap.put(0xFBE7B2, "Banana Mania");
        sNamedColorsMap.put(0x858470, "Bandicoot");
        sNamedColorsMap.put(0xDED717, "Barberry");
        sNamedColorsMap.put(0xA68B5B, "Barley Corn");
        sNamedColorsMap.put(0xFFF4CE, "Barley White");
        sNamedColorsMap.put(0x44012D, "Barossa");
        sNamedColorsMap.put(0x292130, "Bastille");
        sNamedColorsMap.put(0x828F72, "Battleship Gray");
        sNamedColorsMap.put(0x7DA98D, "Bay Leaf");
        sNamedColorsMap.put(0x273A81, "Bay of Many");
        sNamedColorsMap.put(0x98777B, "Bazaar");
        sNamedColorsMap.put(0x3D0C02, "Bean");
        sNamedColorsMap.put(0xEEC1BE, "Beauty Bush");
        sNamedColorsMap.put(0x926F5B, "Beaver");
        sNamedColorsMap.put(0xFEF2C7, "Beeswax");
        sNamedColorsMap.put(0xF5F5DC, "Beige");
        sNamedColorsMap.put(0x7DD8C6, "Bermuda");
        sNamedColorsMap.put(0x6B8BA2, "Bermuda Gray");
        sNamedColorsMap.put(0xDEE5C0, "Beryl Green");
        sNamedColorsMap.put(0xFCFBF3, "Bianca");
        sNamedColorsMap.put(0x162A40, "Big Stone");
        sNamedColorsMap.put(0x327C14, "Bilbao");
        sNamedColorsMap.put(0xB2A1EA, "Biloba Flower");
        sNamedColorsMap.put(0x373021, "Birch");
        sNamedColorsMap.put(0xD4CD16, "Bird Flower");
        sNamedColorsMap.put(0x1B3162, "Biscay");
        sNamedColorsMap.put(0x497183, "Bismark");
        sNamedColorsMap.put(0xC1B7A4, "Bison Hide");
        sNamedColorsMap.put(0x3D2B1F, "Bistre");
        sNamedColorsMap.put(0x868974, "Bitter");
        sNamedColorsMap.put(0xCAE00D, "Bitter Lemon");
        sNamedColorsMap.put(0xFE6F5E, "Bittersweet");
        sNamedColorsMap.put(0xEEDEDA, "Bizarre");
        sNamedColorsMap.put(0x000000, "Black");
        sNamedColorsMap.put(0x081910, "Black Bean");
        sNamedColorsMap.put(0x0B1304, "Black Forest");
        sNamedColorsMap.put(0xF6F7F7, "Black Haze");
        sNamedColorsMap.put(0x3E2C1C, "Black Marlin");
        sNamedColorsMap.put(0x242E16, "Black Olive");
        sNamedColorsMap.put(0x041322, "Black Pearl");
        sNamedColorsMap.put(0x0D0332, "Black Rock");
        sNamedColorsMap.put(0x67032D, "Black Rose");
        sNamedColorsMap.put(0x0A001C, "Black Russian");
        sNamedColorsMap.put(0xF2FAFA, "Black Squeeze");
        sNamedColorsMap.put(0xFFFEF6, "Black White");
        sNamedColorsMap.put(0x4D0135, "Blackberry");
        sNamedColorsMap.put(0x32293A, "Blackcurrant");
        sNamedColorsMap.put(0xFF6600, "Blaze Orange");
        sNamedColorsMap.put(0xFEF3D8, "Bleach White");
        sNamedColorsMap.put(0x2C2133, "Bleached Cedar");
        sNamedColorsMap.put(0xA3E3ED, "Blizzard Blue");
        sNamedColorsMap.put(0xDCB4BC, "Blossom");
        sNamedColorsMap.put(0x0000FF, "Blue");
        sNamedColorsMap.put(0x496679, "Blue Bayoux");
        sNamedColorsMap.put(0x9999CC, "Blue Bell");
        sNamedColorsMap.put(0xF1E9FF, "Blue Chalk");
        sNamedColorsMap.put(0x010D1A, "Blue Charcoal");
        sNamedColorsMap.put(0x0C8990, "Blue Chill");
        sNamedColorsMap.put(0x380474, "Blue Diamond");
        sNamedColorsMap.put(0x204852, "Blue Dianne");
        sNamedColorsMap.put(0x2C0E8C, "Blue Gem");
        sNamedColorsMap.put(0xBFBED8, "Blue Haze");
        sNamedColorsMap.put(0x017987, "Blue Lagoon");
        sNamedColorsMap.put(0x7666C6, "Blue Marguerite");
        sNamedColorsMap.put(0x0066FF, "Blue Ribbon");
        sNamedColorsMap.put(0xD2F6DE, "Blue Romance");
        sNamedColorsMap.put(0x748881, "Blue Smoke");
        sNamedColorsMap.put(0x016162, "Blue Stone");
        sNamedColorsMap.put(0x6456B7, "Blue Violet");
        sNamedColorsMap.put(0x042E4C, "Blue Whale");
        sNamedColorsMap.put(0x13264D, "Blue Zodiac");
        sNamedColorsMap.put(0x18587A, "Blumine");
        sNamedColorsMap.put(0xB44668, "Blush");
        sNamedColorsMap.put(0xFF6FFF, "Blush Pink");
        sNamedColorsMap.put(0xAFB1B8, "Bombay");
        sNamedColorsMap.put(0xE5E0E1, "Bon Jour");
        sNamedColorsMap.put(0x0095B6, "Bondi Blue");
        sNamedColorsMap.put(0xE4D1C0, "Bone");
        sNamedColorsMap.put(0x5C0120, "Bordeaux");
        sNamedColorsMap.put(0x4E2A5A, "Bossanova");
        sNamedColorsMap.put(0x3B91B4, "Boston Blue");
        sNamedColorsMap.put(0xC7DDE5, "Botticelli");
        sNamedColorsMap.put(0x093624, "Bottle Green");
        sNamedColorsMap.put(0x7A7A7A, "Boulder");
        sNamedColorsMap.put(0xAE809E, "Bouquet");
        sNamedColorsMap.put(0xBA6F1E, "Bourbon");
        sNamedColorsMap.put(0x4A2A04, "Bracken");
        sNamedColorsMap.put(0xDEC196, "Brandy");
        sNamedColorsMap.put(0xCD8429, "Brandy Punch");
        sNamedColorsMap.put(0xBB8983, "Brandy Rose");
        sNamedColorsMap.put(0x5DA19F, "Breaker Bay");
        sNamedColorsMap.put(0xC62D42, "Brick Red");
        sNamedColorsMap.put(0xFFFAF4, "Bridal Heath");
        sNamedColorsMap.put(0xFEF0EC, "Bridesmaid");
        sNamedColorsMap.put(0x3C4151, "Bright Gray");
        sNamedColorsMap.put(0x66FF00, "Bright Green");
        sNamedColorsMap.put(0xB10000, "Bright Red");
        sNamedColorsMap.put(0xFED33C, "Bright Sun");
        sNamedColorsMap.put(0x08E8DE, "Bright Turquoise");
        sNamedColorsMap.put(0xF653A6, "Brilliant Rose");
        sNamedColorsMap.put(0xFB607F, "Brink Pink");
        sNamedColorsMap.put(0xABA196, "Bronco");
        sNamedColorsMap.put(0x3F2109, "Bronze");
        sNamedColorsMap.put(0x4E420C, "Bronze Olive");
        sNamedColorsMap.put(0x4D400F, "Bronzetone");
        sNamedColorsMap.put(0xFFEC13, "Broom");
        sNamedColorsMap.put(0x964B00, "Brown");
        sNamedColorsMap.put(0x592804, "Brown Bramble");
        sNamedColorsMap.put(0x492615, "Brown Derby");
        sNamedColorsMap.put(0x401801, "Brown Pod");
        sNamedColorsMap.put(0xAF593E, "Brown Rust");
        sNamedColorsMap.put(0x37290E, "Brown Tumbleweed");
        sNamedColorsMap.put(0xE7FEFF, "Bubbles");
        sNamedColorsMap.put(0x622F30, "Buccaneer");
        sNamedColorsMap.put(0xA8AE9C, "Bud");
        sNamedColorsMap.put(0xC1A004, "Buddha Gold");
        sNamedColorsMap.put(0xF0DC82, "Buff");
        sNamedColorsMap.put(0x480607, "Bulgarian Rose");
        sNamedColorsMap.put(0x864D1E, "Bull Shot");
        sNamedColorsMap.put(0x0D1117, "Bunker");
        sNamedColorsMap.put(0x151F4C, "Bunting");
        sNamedColorsMap.put(0x900020, "Burgundy");
        sNamedColorsMap.put(0x002E20, "Burnham");
        sNamedColorsMap.put(0xFF7034, "Burning Orange");
        sNamedColorsMap.put(0xD99376, "Burning Sand");
        sNamedColorsMap.put(0x420303, "Burnt Maroon");
        sNamedColorsMap.put(0xCC5500, "Burnt Orange");
        sNamedColorsMap.put(0xE97451, "Burnt Sienna");
        sNamedColorsMap.put(0x8A3324, "Burnt Umber");
        sNamedColorsMap.put(0x0D2E1C, "Bush");
        sNamedColorsMap.put(0xF3AD16, "Buttercup");
        sNamedColorsMap.put(0xA1750D, "Buttered Rum");
        sNamedColorsMap.put(0x624E9A, "Butterfly Bush");
        sNamedColorsMap.put(0xFFF1B5, "Buttermilk");
        sNamedColorsMap.put(0xFFFCEA, "Buttery White");
        sNamedColorsMap.put(0x4D0A18, "Cab Sav");
        sNamedColorsMap.put(0xD94972, "Cabaret");
        sNamedColorsMap.put(0x3F4C3A, "Cabbage Pont");
        sNamedColorsMap.put(0x587156, "Cactus");
        sNamedColorsMap.put(0xA9B2C3, "Cadet Blue");
        sNamedColorsMap.put(0xB04C6A, "Cadillac");
        sNamedColorsMap.put(0x6F440C, "Cafe Royale");
        sNamedColorsMap.put(0xE0C095, "Calico");
        sNamedColorsMap.put(0xFE9D04, "California");
        sNamedColorsMap.put(0x31728D, "Calypso");
        sNamedColorsMap.put(0x00581A, "Camarone");
        sNamedColorsMap.put(0x893456, "Camelot");
        sNamedColorsMap.put(0xD9B99B, "Cameo");
        sNamedColorsMap.put(0x3C3910, "Camouflage");
        sNamedColorsMap.put(0x78866B, "Camouflage Green");
        sNamedColorsMap.put(0xD591A4, "Can Can");
        sNamedColorsMap.put(0xF3FB62, "Canary");
        sNamedColorsMap.put(0xFCD917, "Candlelight");
        sNamedColorsMap.put(0xFBEC5D, "Candy Corn");
        sNamedColorsMap.put(0x251706, "Cannon Black");
        sNamedColorsMap.put(0x894367, "Cannon Pink");
        sNamedColorsMap.put(0x3C4443, "Cape Cod");
        sNamedColorsMap.put(0xFEE5AC, "Cape Honey");
        sNamedColorsMap.put(0xA26645, "Cape Palliser");
        sNamedColorsMap.put(0xDCEDB4, "Caper");
        sNamedColorsMap.put(0xFFDDAF, "Caramel");
        sNamedColorsMap.put(0xEEEEE8, "Cararra");
        sNamedColorsMap.put(0x01361C, "Cardin Green");
        sNamedColorsMap.put(0xC41E3A, "Cardinal");
        sNamedColorsMap.put(0x8C055E, "Cardinal Pink");
        sNamedColorsMap.put(0xD29EAA, "Careys Pink");
        sNamedColorsMap.put(0x00CC99, "Caribbean Green");
        sNamedColorsMap.put(0xEA88A8, "Carissma");
        sNamedColorsMap.put(0xF3FFD8, "Carla");
        sNamedColorsMap.put(0x960018, "Carmine");
        sNamedColorsMap.put(0x5C2E01, "Carnaby Tan");
        sNamedColorsMap.put(0xF95A61, "Carnation");
        sNamedColorsMap.put(0xFFA6C9, "Carnation Pink");
        sNamedColorsMap.put(0xF9E0ED, "Carousel Pink");
        sNamedColorsMap.put(0xED9121, "Carrot Orange");
        sNamedColorsMap.put(0xF8B853, "Casablanca");
        sNamedColorsMap.put(0x2F6168, "Casal");
        sNamedColorsMap.put(0x8BA9A5, "Cascade");
        sNamedColorsMap.put(0xE6BEA5, "Cashmere");
        sNamedColorsMap.put(0xADBED1, "Casper");
        sNamedColorsMap.put(0x52001F, "Castro");
        sNamedColorsMap.put(0x062A78, "Catalina Blue");
        sNamedColorsMap.put(0xEEF6F7, "Catskill White");
        sNamedColorsMap.put(0xE3BEBE, "Cavern Pink");
        sNamedColorsMap.put(0x3E1C14, "Cedar");
        sNamedColorsMap.put(0x711A00, "Cedar Wood Finish");
        sNamedColorsMap.put(0xACE1AF, "Celadon");
        sNamedColorsMap.put(0xB8C25D, "Celery");
        sNamedColorsMap.put(0xD1D2CA, "Celeste");
        sNamedColorsMap.put(0x1E385B, "Cello");
        sNamedColorsMap.put(0x163222, "Celtic");
        sNamedColorsMap.put(0x8D7662, "Cement");
        sNamedColorsMap.put(0xFCFFF9, "Ceramic");
        sNamedColorsMap.put(0xDA3287, "Cerise");
        sNamedColorsMap.put(0xDE3163, "Cerise Red");
        sNamedColorsMap.put(0x02A4D3, "Cerulean");
        sNamedColorsMap.put(0x2A52BE, "Cerulean Blue");
        sNamedColorsMap.put(0xFFF4F3, "Chablis");
        sNamedColorsMap.put(0x516E3D, "Chalet Green");
        sNamedColorsMap.put(0xEED794, "Chalky");
        sNamedColorsMap.put(0x354E8C, "Chambray");
        sNamedColorsMap.put(0xEDDCB1, "Chamois");
        sNamedColorsMap.put(0xFAECCC, "Champagne");
        sNamedColorsMap.put(0xF8C3DF, "Chantilly");
        sNamedColorsMap.put(0x292937, "Charade");
        sNamedColorsMap.put(0xFFF3F1, "Chardon");
        sNamedColorsMap.put(0xFFCD8C, "Chardonnay");
        sNamedColorsMap.put(0xBAEEF9, "Charlotte");
        sNamedColorsMap.put(0xD47494, "Charm");
        sNamedColorsMap.put(0x7FFF00, "Chartreuse");
        sNamedColorsMap.put(0xDFFF00, "Chartreuse Yellow");
        sNamedColorsMap.put(0x40A860, "Chateau Green");
        sNamedColorsMap.put(0xBDB3C7, "Chatelle");
        sNamedColorsMap.put(0x175579, "Chathams Blue");
        sNamedColorsMap.put(0x83AA5D, "Chelsea Cucumber");
        sNamedColorsMap.put(0x9E5302, "Chelsea Gem");
        sNamedColorsMap.put(0xDFCD6F, "Chenin");
        sNamedColorsMap.put(0xFCDA98, "Cherokee");
        sNamedColorsMap.put(0x2A0359, "Cherry Pie");
        sNamedColorsMap.put(0x651A14, "Cherrywood");
        sNamedColorsMap.put(0xF8D9E9, "Cherub");
        sNamedColorsMap.put(0xB94E48, "Chestnut");
        sNamedColorsMap.put(0xCD5C5C, "Chestnut Rose");
        sNamedColorsMap.put(0x8581D9, "Chetwode Blue");
        sNamedColorsMap.put(0x5D5C58, "Chicago");
        sNamedColorsMap.put(0xF1FFC8, "Chiffon");
        sNamedColorsMap.put(0xF77703, "Chilean Fire");
        sNamedColorsMap.put(0xFFFDE6, "Chilean Heath");
        sNamedColorsMap.put(0xFCFFE7, "China Ivory");
        sNamedColorsMap.put(0xCEC7A7, "Chino");
        sNamedColorsMap.put(0xA8E3BD, "Chinook");
        sNamedColorsMap.put(0x370202, "Chocolate");
        sNamedColorsMap.put(0x33036B, "Christalle");
        sNamedColorsMap.put(0x67A712, "Christi");
        sNamedColorsMap.put(0xE7730A, "Christine");
        sNamedColorsMap.put(0xE8F1D4, "Chrome White");
        sNamedColorsMap.put(0x0E0E18, "Cinder");
        sNamedColorsMap.put(0xFDE1DC, "Cinderella");
        sNamedColorsMap.put(0xE34234, "Cinnabar");
        sNamedColorsMap.put(0x7B3F00, "Cinnamon");
        sNamedColorsMap.put(0x55280C, "Cioccolato");
        sNamedColorsMap.put(0xFAF7D6, "Citrine White");
        sNamedColorsMap.put(0x9EA91F, "Citron");
        sNamedColorsMap.put(0xA1C50A, "Citrus");
        sNamedColorsMap.put(0x480656, "Clairvoyant");
        sNamedColorsMap.put(0xD4B6AF, "Clam Shell");
        sNamedColorsMap.put(0x7F1734, "Claret");
        sNamedColorsMap.put(0xFBCCE7, "Classic Rose");
        sNamedColorsMap.put(0xBDC8B3, "Clay Ash");
        sNamedColorsMap.put(0x8A8360, "Clay Creek");
        sNamedColorsMap.put(0xE9FFFD, "Clear Day");
        sNamedColorsMap.put(0xE96E00, "Clementine");
        sNamedColorsMap.put(0x371D09, "Clinker");
        sNamedColorsMap.put(0xC7C4BF, "Cloud");
        sNamedColorsMap.put(0x202E54, "Cloud Burst");
        sNamedColorsMap.put(0xACA59F, "Cloudy");
        sNamedColorsMap.put(0x384910, "Clover");
        sNamedColorsMap.put(0x0047AB, "Cobalt");
        sNamedColorsMap.put(0x481C1C, "Cocoa Bean");
        sNamedColorsMap.put(0x301F1E, "Cocoa Brown");
        sNamedColorsMap.put(0xF8F7DC, "Coconut Cream");
        sNamedColorsMap.put(0x0B0B0B, "Cod Gray");
        sNamedColorsMap.put(0x706555, "Coffee");
        sNamedColorsMap.put(0x2A140E, "Coffee Bean");
        sNamedColorsMap.put(0x9F381D, "Cognac");
        sNamedColorsMap.put(0x3F2500, "Cola");
        sNamedColorsMap.put(0xABA0D9, "Cold Purple");
        sNamedColorsMap.put(0xCEBABA, "Cold Turkey");
        sNamedColorsMap.put(0xFFEDBC, "Colonial White");
        sNamedColorsMap.put(0x5C5D75, "Comet");
        sNamedColorsMap.put(0x517C66, "Como");
        sNamedColorsMap.put(0xC9D9D2, "Conch");
        sNamedColorsMap.put(0x7C7B7A, "Concord");
        sNamedColorsMap.put(0xF2F2F2, "Concrete");
        sNamedColorsMap.put(0xE9D75A, "Confetti");
        sNamedColorsMap.put(0x593737, "Congo Brown");
        sNamedColorsMap.put(0x02478E, "Congress Blue");
        sNamedColorsMap.put(0xACDD4D, "Conifer");
        sNamedColorsMap.put(0xC6726B, "Contessa");
        sNamedColorsMap.put(0xB87333, "Copper");
        sNamedColorsMap.put(0x7E3A15, "Copper Canyon");
        sNamedColorsMap.put(0x996666, "Copper Rose");
        sNamedColorsMap.put(0x944747, "Copper Rust");
        sNamedColorsMap.put(0xDA8A67, "Copperfield");
        sNamedColorsMap.put(0xFF7F50, "Coral");
        sNamedColorsMap.put(0xFF4040, "Coral Red");
        sNamedColorsMap.put(0xC7BCA2, "Coral Reef");
        sNamedColorsMap.put(0xA86B6B, "Coral Tree");
        sNamedColorsMap.put(0x606E68, "Corduroy");
        sNamedColorsMap.put(0xC4D0B0, "Coriander");
        sNamedColorsMap.put(0x40291D, "Cork");
        sNamedColorsMap.put(0xE7BF05, "Corn");
        sNamedColorsMap.put(0xF8FACD, "Corn Field");
        sNamedColorsMap.put(0x8B6B0B, "Corn Harvest");
        sNamedColorsMap.put(0x93CCEA, "Cornflower");
        sNamedColorsMap.put(0x6495ED, "Cornflower Blue");
        sNamedColorsMap.put(0xFFB0AC, "Cornflower Lilac");
        sNamedColorsMap.put(0xFAD3A2, "Corvette");
        sNamedColorsMap.put(0x76395D, "Cosmic");
        sNamedColorsMap.put(0xFFD8D9, "Cosmos");
        sNamedColorsMap.put(0x615D30, "Costa Del Sol");
        sNamedColorsMap.put(0xFFB7D5, "Cotton Candy");
        sNamedColorsMap.put(0xC2BDB6, "Cotton Seed");
        sNamedColorsMap.put(0x01371A, "County Green");
        sNamedColorsMap.put(0x4D282D, "Cowboy");
        sNamedColorsMap.put(0xB95140, "Crail");
        sNamedColorsMap.put(0xDB5079, "Cranberry");
        sNamedColorsMap.put(0x462425, "Crater Brown");
        sNamedColorsMap.put(0xFFFDD0, "Cream");
        sNamedColorsMap.put(0xFFE5A0, "Cream Brulee");
        sNamedColorsMap.put(0xF5C85C, "Cream Can");
        sNamedColorsMap.put(0x1E0F04, "Creole");
        sNamedColorsMap.put(0x737829, "Crete");
        sNamedColorsMap.put(0xDC143C, "Crimson");
        sNamedColorsMap.put(0x736D58, "Crocodile");
        sNamedColorsMap.put(0x771F1F, "Crown of Thorns");
        sNamedColorsMap.put(0x1C1208, "Crowshead");
        sNamedColorsMap.put(0xB5ECDF, "Cruise");
        sNamedColorsMap.put(0x004816, "Crusoe");
        sNamedColorsMap.put(0xFD7B33, "Crusta");
        sNamedColorsMap.put(0x924321, "Cumin");
        sNamedColorsMap.put(0xFDFFD5, "Cumulus");
        sNamedColorsMap.put(0xFBBEDA, "Cupid");
        sNamedColorsMap.put(0x2596D1, "Curious Blue");
        sNamedColorsMap.put(0x507672, "Cutty Sark");
        sNamedColorsMap.put(0x00FFFF, "Cyan / Aqua");
        sNamedColorsMap.put(0x003E40, "Cyprus");
        sNamedColorsMap.put(0x012731, "Daintree");
        sNamedColorsMap.put(0xF9E4BC, "Dairy Cream");
        sNamedColorsMap.put(0x4F2398, "Daisy Bush");
        sNamedColorsMap.put(0x6E4B26, "Dallas");
        sNamedColorsMap.put(0xFED85D, "Dandelion");
        sNamedColorsMap.put(0x6093D1, "Danube");
        sNamedColorsMap.put(0x0000C8, "Dark Blue");
        sNamedColorsMap.put(0x770F05, "Dark Burgundy");
        sNamedColorsMap.put(0x3C2005, "Dark Ebony");
        sNamedColorsMap.put(0x0A480D, "Dark Fern");
        sNamedColorsMap.put(0x661010, "Dark Tan");
        sNamedColorsMap.put(0xA6A29A, "Dawn");
        sNamedColorsMap.put(0xF3E9E5, "Dawn Pink");
        sNamedColorsMap.put(0x7AC488, "De York");
        sNamedColorsMap.put(0xD2DA97, "Deco");
        sNamedColorsMap.put(0x220878, "Deep Blue");
        sNamedColorsMap.put(0xE47698, "Deep Blush");
        sNamedColorsMap.put(0x4A3004, "Deep Bronze");
        sNamedColorsMap.put(0x007BA7, "Deep Cerulean");
        sNamedColorsMap.put(0x051040, "Deep Cove");
        sNamedColorsMap.put(0x002900, "Deep Fir");
        sNamedColorsMap.put(0x182D09, "Deep Forest Green");
        sNamedColorsMap.put(0x1B127B, "Deep Koamaru");
        sNamedColorsMap.put(0x412010, "Deep Oak");
        sNamedColorsMap.put(0x082567, "Deep Sapphire");
        sNamedColorsMap.put(0x01826B, "Deep Sea");
        sNamedColorsMap.put(0x095859, "Deep Sea Green");
        sNamedColorsMap.put(0x003532, "Deep Teal");
        sNamedColorsMap.put(0xB09A95, "Del Rio");
        sNamedColorsMap.put(0x396413, "Dell");
        sNamedColorsMap.put(0xA4A49D, "Delta");
        sNamedColorsMap.put(0x7563A8, "Deluge");
        sNamedColorsMap.put(0x1560BD, "Denim");
        sNamedColorsMap.put(0xFFEED8, "Derby");
        sNamedColorsMap.put(0xAE6020, "Desert");
        sNamedColorsMap.put(0xEDC9AF, "Desert Sand");
        sNamedColorsMap.put(0xF8F8F7, "Desert Storm");
        sNamedColorsMap.put(0xEAFFFE, "Dew");
        sNamedColorsMap.put(0xDB995E, "Di Serria");
        sNamedColorsMap.put(0x130000, "Diesel");
        sNamedColorsMap.put(0x5D7747, "Dingley");
        sNamedColorsMap.put(0x871550, "Disco");
        sNamedColorsMap.put(0xE29418, "Dixie");
        sNamedColorsMap.put(0x1E90FF, "Dodger Blue");
        sNamedColorsMap.put(0xF9FF8B, "Dolly");
        sNamedColorsMap.put(0x646077, "Dolphin");
        sNamedColorsMap.put(0x8E775E, "Domino");
        sNamedColorsMap.put(0x5D4C51, "Don Juan");
        sNamedColorsMap.put(0xA69279, "Donkey Brown");
        sNamedColorsMap.put(0x6B5755, "Dorado");
        sNamedColorsMap.put(0xEEE3AD, "Double Colonial White");
        sNamedColorsMap.put(0xFCF4D0, "Double Pearl Lusta");
        sNamedColorsMap.put(0xE6D7B9, "Double Spanish White");
        sNamedColorsMap.put(0x6D6C6C, "Dove Gray");
        sNamedColorsMap.put(0x092256, "Downriver");
        sNamedColorsMap.put(0x6FD0C5, "Downy");
        sNamedColorsMap.put(0xAF8751, "Driftwood");
        sNamedColorsMap.put(0xFDF7AD, "Drover");
        sNamedColorsMap.put(0xA899E6, "Dull Lavender");
        sNamedColorsMap.put(0x383533, "Dune");
        sNamedColorsMap.put(0xE5CCC9, "Dust Storm");
        sNamedColorsMap.put(0xA8989B, "Dusty Gray");
        sNamedColorsMap.put(0xB6BAA4, "Eagle");
        sNamedColorsMap.put(0xC9B93B, "Earls Green");
        sNamedColorsMap.put(0xFFF9E6, "Early Dawn");
        sNamedColorsMap.put(0x414C7D, "East Bay");
        sNamedColorsMap.put(0xAC91CE, "East Side");
        sNamedColorsMap.put(0x1E9AB0, "Eastern Blue");
        sNamedColorsMap.put(0xE9E3E3, "Ebb");
        sNamedColorsMap.put(0x0C0B1D, "Ebony");
        sNamedColorsMap.put(0x26283B, "Ebony Clay");
        sNamedColorsMap.put(0x311C17, "Eclipse");
        sNamedColorsMap.put(0xF5F3E5, "Ecru White");
        sNamedColorsMap.put(0xFA7814, "Ecstasy");
        sNamedColorsMap.put(0x105852, "Eden");
        sNamedColorsMap.put(0xC8E3D7, "Edgewater");
        sNamedColorsMap.put(0xA2AEAB, "Edward");
        sNamedColorsMap.put(0xFFF4DD, "Egg Sour");
        sNamedColorsMap.put(0xFFEFC1, "Egg White");
        sNamedColorsMap.put(0x614051, "Eggplant");
        sNamedColorsMap.put(0x1E1708, "El Paso");
        sNamedColorsMap.put(0x8F3E33, "El Salva");
        sNamedColorsMap.put(0xCCFF00, "Electric Lime");
        sNamedColorsMap.put(0x8B00FF, "Electric Violet");
        sNamedColorsMap.put(0x123447, "Elephant");
        sNamedColorsMap.put(0x088370, "Elf Green");
        sNamedColorsMap.put(0x1C7C7D, "Elm");
        sNamedColorsMap.put(0x50C878, "Emerald");
        sNamedColorsMap.put(0x6C3082, "Eminence");
        sNamedColorsMap.put(0x514649, "Emperor");
        sNamedColorsMap.put(0x817377, "Empress");
        sNamedColorsMap.put(0x0056A7, "Endeavour");
        sNamedColorsMap.put(0xF8DD5C, "Energy Yellow");
        sNamedColorsMap.put(0x022D15, "English Holly");
        sNamedColorsMap.put(0x3E2B23, "English Walnut");
        sNamedColorsMap.put(0x8BA690, "Envy");
        sNamedColorsMap.put(0xE1BC64, "Equator");
        sNamedColorsMap.put(0x612718, "Espresso");
        sNamedColorsMap.put(0x211A0E, "Eternity");
        sNamedColorsMap.put(0x278A5B, "Eucalyptus");
        sNamedColorsMap.put(0xCFA39D, "Eunry");
        sNamedColorsMap.put(0x024E46, "Evening Sea");
        sNamedColorsMap.put(0x1C402E, "Everglade");
        sNamedColorsMap.put(0x427977, "Faded Jade");
        sNamedColorsMap.put(0xFFEFEC, "Fair Pink");
        sNamedColorsMap.put(0x7F626D, "Falcon");
        sNamedColorsMap.put(0xECEBBD, "Fall Green");
        sNamedColorsMap.put(0x801818, "Falu Red");
        sNamedColorsMap.put(0xFAF3F0, "Fantasy");
        sNamedColorsMap.put(0x796A78, "Fedora");
        sNamedColorsMap.put(0x9FDD8C, "Feijoa");
        sNamedColorsMap.put(0x63B76C, "Fern");
        sNamedColorsMap.put(0x657220, "Fern Frond");
        sNamedColorsMap.put(0x4F7942, "Fern Green");
        sNamedColorsMap.put(0x704F50, "Ferra");
        sNamedColorsMap.put(0xFBE96C, "Festival");
        sNamedColorsMap.put(0xF0FCEA, "Feta");
        sNamedColorsMap.put(0xB35213, "Fiery Orange");
        sNamedColorsMap.put(0x626649, "Finch");
        sNamedColorsMap.put(0x556D56, "Finlandia");
        sNamedColorsMap.put(0x692D54, "Finn");
        sNamedColorsMap.put(0x405169, "Fiord");
        sNamedColorsMap.put(0xAA4203, "Fire");
        sNamedColorsMap.put(0xE89928, "Fire Bush");
        sNamedColorsMap.put(0x0E2A30, "Firefly");
        sNamedColorsMap.put(0xDA5B38, "Flame Pea");
        sNamedColorsMap.put(0xFF7D07, "Flamenco");
        sNamedColorsMap.put(0xF2552A, "Flamingo");
        sNamedColorsMap.put(0xEEDC82, "Flax");
        sNamedColorsMap.put(0x7B8265, "Flax Smoke");
        sNamedColorsMap.put(0xFFCBA4, "Flesh");
        sNamedColorsMap.put(0x6F6A61, "Flint");
        sNamedColorsMap.put(0xA2006D, "Flirt");
        sNamedColorsMap.put(0xCA3435, "Flush Mahogany");
        sNamedColorsMap.put(0xFF7F00, "Flush Orange");
        sNamedColorsMap.put(0xD8FCFA, "Foam");
        sNamedColorsMap.put(0xD7D0FF, "Fog");
        sNamedColorsMap.put(0xCBCAB6, "Foggy Gray");
        sNamedColorsMap.put(0x228B22, "Forest Green");
        sNamedColorsMap.put(0xFFF1EE, "Forget Me Not");
        sNamedColorsMap.put(0x56B4BE, "Fountain Blue");
        sNamedColorsMap.put(0xFFDEB3, "Frangipani");
        sNamedColorsMap.put(0xBDBDC6, "French Gray");
        sNamedColorsMap.put(0xECC7EE, "French Lilac");
        sNamedColorsMap.put(0xBDEDFD, "French Pass");
        sNamedColorsMap.put(0xF64A8A, "French Rose");
        sNamedColorsMap.put(0x990066, "Fresh Eggplant");
        sNamedColorsMap.put(0x807E79, "Friar Gray");
        sNamedColorsMap.put(0xB1E2C1, "Fringy Flower");
        sNamedColorsMap.put(0xF57584, "Froly");
        sNamedColorsMap.put(0xEDF5DD, "Frost");
        sNamedColorsMap.put(0xDBFFF8, "Frosted Mint");
        sNamedColorsMap.put(0xE4F6E7, "Frostee");
        sNamedColorsMap.put(0x4F9D5D, "Fruit Salad");
        sNamedColorsMap.put(0x7A58C1, "Fuchsia Blue");
        sNamedColorsMap.put(0xC154C1, "Fuchsia Pink");
        sNamedColorsMap.put(0xBEDE0D, "Fuego");
        sNamedColorsMap.put(0xECA927, "Fuel Yellow");
        sNamedColorsMap.put(0x1959A8, "Fun Blue");
        sNamedColorsMap.put(0x016D39, "Fun Green");
        sNamedColorsMap.put(0x54534D, "Fuscous Gray");
        sNamedColorsMap.put(0xC45655, "Fuzzy Wuzzy Brown");
        sNamedColorsMap.put(0x163531, "Gable Green");
        sNamedColorsMap.put(0xEFEFEF, "Gallery");
        sNamedColorsMap.put(0xDCB20C, "Galliano");
        sNamedColorsMap.put(0xE49B0F, "Gamboge");
        sNamedColorsMap.put(0xD18F1B, "Geebung");
        sNamedColorsMap.put(0x15736B, "Genoa");
        sNamedColorsMap.put(0xFB8989, "Geraldine");
        sNamedColorsMap.put(0xD4DFE2, "Geyser");
        sNamedColorsMap.put(0xC7C9D5, "Ghost");
        sNamedColorsMap.put(0x523C94, "Gigas");
        sNamedColorsMap.put(0xB8B56A, "Gimblet");
        sNamedColorsMap.put(0xE8F2EB, "Gin");
        sNamedColorsMap.put(0xFFF9E2, "Gin Fizz");
        sNamedColorsMap.put(0xF8E4BF, "Givry");
        sNamedColorsMap.put(0x80B3C4, "Glacier");
        sNamedColorsMap.put(0x61845F, "Glade Green");
        sNamedColorsMap.put(0x726D4E, "Go Ben");
        sNamedColorsMap.put(0x3D7D52, "Goblin");
        sNamedColorsMap.put(0xFFD700, "Gold");
        sNamedColorsMap.put(0xF18200, "Gold Drop");
        sNamedColorsMap.put(0xE6BE8A, "Gold Sand");
        sNamedColorsMap.put(0xDEBA13, "Gold Tips");
        sNamedColorsMap.put(0xE28913, "Golden Bell");
        sNamedColorsMap.put(0xF0D52D, "Golden Dream");
        sNamedColorsMap.put(0xF5FB3D, "Golden Fizz");
        sNamedColorsMap.put(0xFDE295, "Golden Glow");
        sNamedColorsMap.put(0xDAA520, "Golden Grass");
        sNamedColorsMap.put(0xF0DB7D, "Golden Sand");
        sNamedColorsMap.put(0xFFCC5C, "Golden Tainoi");
        sNamedColorsMap.put(0xFCD667, "Goldenrod");
        sNamedColorsMap.put(0x261414, "Gondola");
        sNamedColorsMap.put(0x0B1107, "Gordons Green");
        sNamedColorsMap.put(0xFFF14F, "Gorse");
        sNamedColorsMap.put(0x069B81, "Gossamer");
        sNamedColorsMap.put(0xD2F8B0, "Gossip");
        sNamedColorsMap.put(0x6D92A1, "Gothic");
        sNamedColorsMap.put(0x2F3CB3, "Governor Bay");
        sNamedColorsMap.put(0xE4D5B7, "Grain Brown");
        sNamedColorsMap.put(0xFFD38C, "Grandis");
        sNamedColorsMap.put(0x8D8974, "Granite Green");
        sNamedColorsMap.put(0xD5F6E3, "Granny Apple");
        sNamedColorsMap.put(0x84A0A0, "Granny Smith");
        sNamedColorsMap.put(0x9DE093, "Granny Smith Apple");
        sNamedColorsMap.put(0x381A51, "Grape");
        sNamedColorsMap.put(0x251607, "Graphite");
        sNamedColorsMap.put(0x4A444B, "Gravel");
        sNamedColorsMap.put(0x808080, "Gray");
        sNamedColorsMap.put(0x465945, "Gray Asparagus");
        sNamedColorsMap.put(0xA2AAB3, "Gray Chateau");
        sNamedColorsMap.put(0xC3C3BD, "Gray Nickel");
        sNamedColorsMap.put(0xE7ECE6, "Gray Nurse");
        sNamedColorsMap.put(0xA9A491, "Gray Olive");
        sNamedColorsMap.put(0xC1BECD, "Gray Suit");
        sNamedColorsMap.put(0x00FF00, "Green");
        sNamedColorsMap.put(0x01A368, "Green Haze");
        sNamedColorsMap.put(0x24500F, "Green House");
        sNamedColorsMap.put(0x25311C, "Green Kelp");
        sNamedColorsMap.put(0x436A0D, "Green Leaf");
        sNamedColorsMap.put(0xCBD3B0, "Green Mist");
        sNamedColorsMap.put(0x1D6142, "Green Pea");
        sNamedColorsMap.put(0xA4AF6E, "Green Smoke");
        sNamedColorsMap.put(0xB8C1B1, "Green Spring");
        sNamedColorsMap.put(0x032B52, "Green Vogue");
        sNamedColorsMap.put(0x101405, "Green Waterloo");
        sNamedColorsMap.put(0xE8EBE0, "Green White");
        sNamedColorsMap.put(0xADFF2F, "Green Yellow");
        sNamedColorsMap.put(0xD54600, "Grenadier");
        sNamedColorsMap.put(0xBA0101, "Guardsman Red");
        sNamedColorsMap.put(0x051657, "Gulf Blue");
        sNamedColorsMap.put(0x80B3AE, "Gulf Stream");
        sNamedColorsMap.put(0x9DACB7, "Gull Gray");
        sNamedColorsMap.put(0xB6D3BF, "Gum Leaf");
        sNamedColorsMap.put(0x7CA1A6, "Gumbo");
        sNamedColorsMap.put(0x414257, "Gun Powder");
        sNamedColorsMap.put(0x828685, "Gunsmoke");
        sNamedColorsMap.put(0x9A9577, "Gurkha");
        sNamedColorsMap.put(0x98811B, "Hacienda");
        sNamedColorsMap.put(0x6B2A14, "Hairy Heath");
        sNamedColorsMap.put(0x1B1035, "Haiti");
        sNamedColorsMap.put(0xFFFEE1, "Half and Half");
        sNamedColorsMap.put(0x85C4CC, "Half Baked");
        sNamedColorsMap.put(0xFDF6D3, "Half Colonial White");
        sNamedColorsMap.put(0xFEF7DE, "Half Dutch White");
        sNamedColorsMap.put(0xFEF4DB, "Half Spanish White");
        sNamedColorsMap.put(0xE5D8AF, "Hampton");
        sNamedColorsMap.put(0x3FFF00, "Harlequin");
        sNamedColorsMap.put(0xE6F2EA, "Harp");
        sNamedColorsMap.put(0xE0B974, "Harvest Gold");
        sNamedColorsMap.put(0x5590D9, "Havelock Blue");
        sNamedColorsMap.put(0x9D5616, "Hawaiian Tan");
        sNamedColorsMap.put(0xD4E2FC, "Hawkes Blue");
        sNamedColorsMap.put(0x541012, "Heath");
        sNamedColorsMap.put(0xB7C3D0, "Heather");
        sNamedColorsMap.put(0xB6B095, "Heathered Gray");
        sNamedColorsMap.put(0x2B3228, "Heavy Metal");
        sNamedColorsMap.put(0xDF73FF, "Heliotrope");
        sNamedColorsMap.put(0x5E5D3B, "Hemlock");
        sNamedColorsMap.put(0x907874, "Hemp");
        sNamedColorsMap.put(0xB6316C, "Hibiscus");
        sNamedColorsMap.put(0x6F8E63, "Highland");
        sNamedColorsMap.put(0xACA586, "Hillary");
        sNamedColorsMap.put(0x6A5D1B, "Himalaya");
        sNamedColorsMap.put(0xE6FFE9, "Hint of Green");
        sNamedColorsMap.put(0xFBF9F9, "Hint of Red");
        sNamedColorsMap.put(0xFAFDE4, "Hint of Yellow");
        sNamedColorsMap.put(0x589AAF, "Hippie Blue");
        sNamedColorsMap.put(0x53824B, "Hippie Green");
        sNamedColorsMap.put(0xAE4560, "Hippie Pink");
        sNamedColorsMap.put(0xA1ADB5, "Hit Gray");
        sNamedColorsMap.put(0xFFAB81, "Hit Pink");
        sNamedColorsMap.put(0xC8A528, "Hokey Pokey");
        sNamedColorsMap.put(0x65869F, "Hoki");
        sNamedColorsMap.put(0x011D13, "Holly");
        sNamedColorsMap.put(0xF400A1, "Hollywood Cerise");
        sNamedColorsMap.put(0x4F1C70, "Honey Flower");
        sNamedColorsMap.put(0xEDFC84, "Honeysuckle");
        sNamedColorsMap.put(0xD06DA1, "Hopbush");
        sNamedColorsMap.put(0x5A87A0, "Horizon");
        sNamedColorsMap.put(0x604913, "Horses Neck");
        sNamedColorsMap.put(0xD2691E, "Hot Cinnamon");
        sNamedColorsMap.put(0xFF69B4, "Hot Pink");
        sNamedColorsMap.put(0xB38007, "Hot Toddy");
        sNamedColorsMap.put(0xCFF9F3, "Humming Bird");
        sNamedColorsMap.put(0x161D10, "Hunter Green");
        sNamedColorsMap.put(0x877C7B, "Hurricane");
        sNamedColorsMap.put(0xB7A458, "Husk");
        sNamedColorsMap.put(0xB1F4E7, "Ice Cold");
        sNamedColorsMap.put(0xDAF4F0, "Iceberg");
        sNamedColorsMap.put(0xF6A4C9, "Illusion");
        sNamedColorsMap.put(0xB0E313, "Inch Worm");
        sNamedColorsMap.put(0xC3B091, "Indian Khaki");
        sNamedColorsMap.put(0x4D1E01, "Indian Tan");
        sNamedColorsMap.put(0x4F69C6, "Indigo");
        sNamedColorsMap.put(0xC26B03, "Indochine");
        sNamedColorsMap.put(0x002FA7, "International Klein Blue");
        sNamedColorsMap.put(0xFF4F00, "International Orange");
        sNamedColorsMap.put(0x5F3D26, "Irish Coffee");
        sNamedColorsMap.put(0x433120, "Iroko");
        sNamedColorsMap.put(0xD4D7D9, "Iron");
        sNamedColorsMap.put(0x676662, "Ironside Gray");
        sNamedColorsMap.put(0x86483C, "Ironstone");
        sNamedColorsMap.put(0xFFFCEE, "Island Spice");
        sNamedColorsMap.put(0xFFFFF0, "Ivory");
        sNamedColorsMap.put(0x2E0329, "Jacaranda");
        sNamedColorsMap.put(0x3A2A6A, "Jacarta");
        sNamedColorsMap.put(0x2E1905, "Jacko Bean");
        sNamedColorsMap.put(0x20208D, "Jacksons Purple");
        sNamedColorsMap.put(0x00A86B, "Jade");
        sNamedColorsMap.put(0xEF863F, "Jaffa");
        sNamedColorsMap.put(0xC2E8E5, "Jagged Ice");
        sNamedColorsMap.put(0x350E57, "Jagger");
        sNamedColorsMap.put(0x080110, "Jaguar");
        sNamedColorsMap.put(0x5B3013, "Jambalaya");
        sNamedColorsMap.put(0xF4EBD3, "Janna");
        sNamedColorsMap.put(0x0A6906, "Japanese Laurel");
        sNamedColorsMap.put(0x780109, "Japanese Maple");
        sNamedColorsMap.put(0xD87C63, "Japonica");
        sNamedColorsMap.put(0x1FC2C2, "Java");
        sNamedColorsMap.put(0xA50B5E, "Jazzberry Jam");
        sNamedColorsMap.put(0x297B9A, "Jelly Bean");
        sNamedColorsMap.put(0xB5D2CE, "Jet Stream");
        sNamedColorsMap.put(0x126B40, "Jewel");
        sNamedColorsMap.put(0x3B1F1F, "Jon");
        sNamedColorsMap.put(0xEEFF9A, "Jonquil");
        sNamedColorsMap.put(0x8AB9F1, "Jordy Blue");
        sNamedColorsMap.put(0x544333, "Judge Gray");
        sNamedColorsMap.put(0x7C7B82, "Jumbo");
        sNamedColorsMap.put(0x29AB87, "Jungle Green");
        sNamedColorsMap.put(0xB4CFD3, "Jungle Mist");
        sNamedColorsMap.put(0x6D9292, "Juniper");
        sNamedColorsMap.put(0xECCDB9, "Just Right");
        sNamedColorsMap.put(0x5E483E, "Kabul");
        sNamedColorsMap.put(0x004620, "Kaitoke Green");
        sNamedColorsMap.put(0xC6C8BD, "Kangaroo");
        sNamedColorsMap.put(0x1E1609, "Karaka");
        sNamedColorsMap.put(0xFFEAD4, "Karry");
        sNamedColorsMap.put(0x507096, "Kashmir Blue");
        sNamedColorsMap.put(0x454936, "Kelp");
        sNamedColorsMap.put(0x7C1C05, "Kenyan Copper");
        sNamedColorsMap.put(0x3AB09E, "Keppel");
        sNamedColorsMap.put(0xBFC921, "Key Lime Pie");
        sNamedColorsMap.put(0xF0E68C, "Khaki");
        sNamedColorsMap.put(0xE1EAD4, "Kidnapper");
        sNamedColorsMap.put(0x240C02, "Kilamanjaro");
        sNamedColorsMap.put(0x3A6A47, "Killarney");
        sNamedColorsMap.put(0x736C9F, "Kimberly");
        sNamedColorsMap.put(0x3E0480, "Kingfisher Daisy");
        sNamedColorsMap.put(0xE79FC4, "Kobi");
        sNamedColorsMap.put(0x6E6D57, "Kokoda");
        sNamedColorsMap.put(0x8F4B0E, "Korma");
        sNamedColorsMap.put(0xFFBD5F, "Koromiko");
        sNamedColorsMap.put(0xFFE772, "Kournikova");
        sNamedColorsMap.put(0x886221, "Kumera");
        sNamedColorsMap.put(0x368716, "La Palma");
        sNamedColorsMap.put(0xB3C110, "La Rioja");
        sNamedColorsMap.put(0xC6E610, "Las Palmas");
        sNamedColorsMap.put(0xC8B568, "Laser");
        sNamedColorsMap.put(0xFFFF66, "Laser Lemon");
        sNamedColorsMap.put(0x749378, "Laurel");
        sNamedColorsMap.put(0xB57EDC, "Lavender");
        sNamedColorsMap.put(0xFFF0F5, "Lavender blush");
        sNamedColorsMap.put(0xBDBBD7, "Lavender Gray");
        sNamedColorsMap.put(0xEE82EE, "Lavender Magenta");
        sNamedColorsMap.put(0xFBAED2, "Lavender Pink");
        sNamedColorsMap.put(0x967BB6, "Lavender Purple");
        sNamedColorsMap.put(0xFBA0E3, "Lavender Rose");
        sNamedColorsMap.put(0x967059, "Leather");
        sNamedColorsMap.put(0xFDE910, "Lemon");
        sNamedColorsMap.put(0xFFFACD, "Lemon Chiffon");
        sNamedColorsMap.put(0xAC9E22, "Lemon Ginger");
        sNamedColorsMap.put(0x9B9E8F, "Lemon Grass");
        sNamedColorsMap.put(0xFDD5B1, "Light Apricot");
        sNamedColorsMap.put(0xE29CD2, "Light Orchid");
        sNamedColorsMap.put(0xC9A0DC, "Light Wisteria");
        sNamedColorsMap.put(0xFCC01E, "Lightning Yellow");
        sNamedColorsMap.put(0xC8A2C8, "Lilac");
        sNamedColorsMap.put(0x9874D3, "Lilac Bush");
        sNamedColorsMap.put(0xC8AABF, "Lily");
        sNamedColorsMap.put(0xE7F8FF, "Lily White");
        sNamedColorsMap.put(0x76BD17, "Lima");
        sNamedColorsMap.put(0xBFFF00, "Lime");
        sNamedColorsMap.put(0x6F9D02, "Limeade");
        sNamedColorsMap.put(0x747D63, "Limed Ash");
        sNamedColorsMap.put(0xAC8A56, "Limed Oak");
        sNamedColorsMap.put(0x394851, "Limed Spruce");
        sNamedColorsMap.put(0xFAF0E6, "Linen");
        sNamedColorsMap.put(0xD9E4F5, "Link Water");
        sNamedColorsMap.put(0xAB0563, "Lipstick");
        sNamedColorsMap.put(0x423921, "Lisbon Brown");
        sNamedColorsMap.put(0x4D282E, "Livid Brown");
        sNamedColorsMap.put(0xEEF4DE, "Loafer");
        sNamedColorsMap.put(0xBDC9CE, "Loblolly");
        sNamedColorsMap.put(0x2C8C84, "Lochinvar");
        sNamedColorsMap.put(0x007EC7, "Lochmara");
        sNamedColorsMap.put(0xA8AF8E, "Locust");
        sNamedColorsMap.put(0x242A1D, "Log Cabin");
        sNamedColorsMap.put(0xAAA9CD, "Logan");
        sNamedColorsMap.put(0xDFCFDB, "Lola");
        sNamedColorsMap.put(0xBEA6C3, "London Hue");
        sNamedColorsMap.put(0x6D0101, "Lonestar");
        sNamedColorsMap.put(0x863C3C, "Lotus");
        sNamedColorsMap.put(0x460B41, "Loulou");
        sNamedColorsMap.put(0xAF9F1C, "Lucky");
        sNamedColorsMap.put(0x1A1A68, "Lucky Point");
        sNamedColorsMap.put(0x3C493A, "Lunar Green");
        sNamedColorsMap.put(0xA7882C, "Luxor Gold");
        sNamedColorsMap.put(0x697E9A, "Lynch");
        sNamedColorsMap.put(0xD9F7FF, "Mabel");
        sNamedColorsMap.put(0xFFB97B, "Macaroni and Cheese");
        sNamedColorsMap.put(0xB7F0BE, "Madang");
        sNamedColorsMap.put(0x09255D, "Madison");
        sNamedColorsMap.put(0x3F3002, "Madras");
        sNamedColorsMap.put(0xFF00FF, "Magenta / Fuchsia");
        sNamedColorsMap.put(0xAAF0D1, "Magic Mint");
        sNamedColorsMap.put(0xF8F4FF, "Magnolia");
        sNamedColorsMap.put(0x4E0606, "Mahogany");
        sNamedColorsMap.put(0xB06608, "Mai Tai");
        sNamedColorsMap.put(0xF5D5A0, "Maize");
        sNamedColorsMap.put(0x897D6D, "Makara");
        sNamedColorsMap.put(0x444954, "Mako");
        sNamedColorsMap.put(0x0BDA51, "Malachite");
        sNamedColorsMap.put(0x7DC8F7, "Malibu");
        sNamedColorsMap.put(0x233418, "Mallard");
        sNamedColorsMap.put(0xBDB2A1, "Malta");
        sNamedColorsMap.put(0x8E8190, "Mamba");
        sNamedColorsMap.put(0x8D90A1, "Manatee");
        sNamedColorsMap.put(0xAD781B, "Mandalay");
        sNamedColorsMap.put(0xE25465, "Mandy");
        sNamedColorsMap.put(0xF2C3B2, "Mandys Pink");
        sNamedColorsMap.put(0xE77200, "Mango Tango");
        sNamedColorsMap.put(0xF5C999, "Manhattan");
        sNamedColorsMap.put(0x74C365, "Mantis");
        sNamedColorsMap.put(0x8B9C90, "Mantle");
        sNamedColorsMap.put(0xEEEF78, "Manz");
        sNamedColorsMap.put(0x350036, "Mardi Gras");
        sNamedColorsMap.put(0xB98D28, "Marigold");
        sNamedColorsMap.put(0xFBE870, "Marigold Yellow");
        sNamedColorsMap.put(0x286ACD, "Mariner");
        sNamedColorsMap.put(0x800000, "Maroon");
        sNamedColorsMap.put(0xC32148, "Maroon Flush");
        sNamedColorsMap.put(0x520C17, "Maroon Oak");
        sNamedColorsMap.put(0x0B0F08, "Marshland");
        sNamedColorsMap.put(0xAFA09E, "Martini");
        sNamedColorsMap.put(0x363050, "Martinique");
        sNamedColorsMap.put(0xF8DB9D, "Marzipan");
        sNamedColorsMap.put(0x403B38, "Masala");
        sNamedColorsMap.put(0x1B659D, "Matisse");
        sNamedColorsMap.put(0xB05D54, "Matrix");
        sNamedColorsMap.put(0x4E3B41, "Matterhorn");
        sNamedColorsMap.put(0xE0B0FF, "Mauve");
        sNamedColorsMap.put(0xF091A9, "Mauvelous");
        sNamedColorsMap.put(0xD8C2D5, "Maverick");
        sNamedColorsMap.put(0xAF4035, "Medium Carmine");
        sNamedColorsMap.put(0x9370DB, "Medium Purple");
        sNamedColorsMap.put(0xBB3385, "Medium Red Violet");
        sNamedColorsMap.put(0xE4C2D5, "Melanie");
        sNamedColorsMap.put(0x300529, "Melanzane");
        sNamedColorsMap.put(0xFEBAAD, "Melon");
        sNamedColorsMap.put(0xC7C1FF, "Melrose");
        sNamedColorsMap.put(0xE5E5E5, "Mercury");
        sNamedColorsMap.put(0xF6F0E6, "Merino");
        sNamedColorsMap.put(0x413C37, "Merlin");
        sNamedColorsMap.put(0x831923, "Merlot");
        sNamedColorsMap.put(0x49371B, "Metallic Bronze");
        sNamedColorsMap.put(0x71291D, "Metallic Copper");
        sNamedColorsMap.put(0xD07D12, "Meteor");
        sNamedColorsMap.put(0x3C1F76, "Meteorite");
        sNamedColorsMap.put(0xA72525, "Mexican Red");
        sNamedColorsMap.put(0x5F5F6E, "Mid Gray");
        sNamedColorsMap.put(0x011635, "Midnight");
        sNamedColorsMap.put(0x003366, "Midnight Blue");
        sNamedColorsMap.put(0x041004, "Midnight Moss");
        sNamedColorsMap.put(0x2D2510, "Mikado");
        sNamedColorsMap.put(0xFAFFA4, "Milan");
        sNamedColorsMap.put(0xB81104, "Milano Red");
        sNamedColorsMap.put(0xFFF6D4, "Milk Punch");
        sNamedColorsMap.put(0x594433, "Millbrook");
        sNamedColorsMap.put(0xF8FDD3, "Mimosa");
        sNamedColorsMap.put(0xE3F988, "Mindaro");
        sNamedColorsMap.put(0x323232, "Mine Shaft");
        sNamedColorsMap.put(0x3F5D53, "Mineral Green");
        sNamedColorsMap.put(0x36747D, "Ming");
        sNamedColorsMap.put(0x3F307F, "Minsk");
        sNamedColorsMap.put(0x98FF98, "Mint Green");
        sNamedColorsMap.put(0xF1EEC1, "Mint Julep");
        sNamedColorsMap.put(0xC4F4EB, "Mint Tulip");
        sNamedColorsMap.put(0x161928, "Mirage");
        sNamedColorsMap.put(0xD1D2DD, "Mischka");
        sNamedColorsMap.put(0xC4C4BC, "Mist Gray");
        sNamedColorsMap.put(0x7F7589, "Mobster");
        sNamedColorsMap.put(0x6E1D14, "Moccaccino");
        sNamedColorsMap.put(0x782D19, "Mocha");
        sNamedColorsMap.put(0xC04737, "Mojo");
        sNamedColorsMap.put(0xFFA194, "Mona Lisa");
        sNamedColorsMap.put(0x8B0723, "Monarch");
        sNamedColorsMap.put(0x4A3C30, "Mondo");
        sNamedColorsMap.put(0xB5A27F, "Mongoose");
        sNamedColorsMap.put(0x8A8389, "Monsoon");
        sNamedColorsMap.put(0x83D0C6, "Monte Carlo");
        sNamedColorsMap.put(0xC7031E, "Monza");
        sNamedColorsMap.put(0x7F76D3, "Moody Blue");
        sNamedColorsMap.put(0xFCFEDA, "Moon Glow");
        sNamedColorsMap.put(0xDCDDCC, "Moon Mist");
        sNamedColorsMap.put(0xD6CEF6, "Moon Raker");
        sNamedColorsMap.put(0x9EDEE0, "Morning Glory");
        sNamedColorsMap.put(0x441D00, "Morocco Brown");
        sNamedColorsMap.put(0x504351, "Mortar");
        sNamedColorsMap.put(0x036A6E, "Mosque");
        sNamedColorsMap.put(0xADDFAD, "Moss Green");
        sNamedColorsMap.put(0x1AB385, "Mountain Meadow");
        sNamedColorsMap.put(0x959396, "Mountain Mist");
        sNamedColorsMap.put(0x997A8D, "Mountbatten Pink");
        sNamedColorsMap.put(0xB78E5C, "Muddy Waters");
        sNamedColorsMap.put(0xAA8B5B, "Muesli");
        sNamedColorsMap.put(0xC54B8C, "Mulberry");
        sNamedColorsMap.put(0x5C0536, "Mulberry Wood");
        sNamedColorsMap.put(0x8C472F, "Mule Fawn");
        sNamedColorsMap.put(0x4E4562, "Mulled Wine");
        sNamedColorsMap.put(0xFFDB58, "Mustard");
        sNamedColorsMap.put(0xD69188, "My Pink");
        sNamedColorsMap.put(0xFFB31F, "My Sin");
        sNamedColorsMap.put(0xE2EBED, "Mystic");
        sNamedColorsMap.put(0x4B5D52, "Nandor");
        sNamedColorsMap.put(0xACA494, "Napa");
        sNamedColorsMap.put(0xEDF9F1, "Narvik");
        sNamedColorsMap.put(0x8B8680, "Natural Gray");
        sNamedColorsMap.put(0xFFDEAD, "Navajo White");
        sNamedColorsMap.put(0x000080, "Navy Blue");
        sNamedColorsMap.put(0xCBDBD6, "Nebula");
        sNamedColorsMap.put(0xFFE2C5, "Negroni");
        sNamedColorsMap.put(0xFF9933, "Neon Carrot");
        sNamedColorsMap.put(0x8EABC1, "Nepal");
        sNamedColorsMap.put(0x7CB7BB, "Neptune");
        sNamedColorsMap.put(0x140600, "Nero");
        sNamedColorsMap.put(0x646E75, "Nevada");
        sNamedColorsMap.put(0xF3D69D, "New Orleans");
        sNamedColorsMap.put(0xD7837F, "New York Pink");
        sNamedColorsMap.put(0x06A189, "Niagara");
        sNamedColorsMap.put(0x1F120F, "Night Rider");
        sNamedColorsMap.put(0xAA375A, "Night Shadz");
        sNamedColorsMap.put(0x193751, "Nile Blue");
        sNamedColorsMap.put(0xB7B1B1, "Nobel");
        sNamedColorsMap.put(0xBAB1A2, "Nomad");
        sNamedColorsMap.put(0xA8BD9F, "Norway");
        sNamedColorsMap.put(0xC59922, "Nugget");
        sNamedColorsMap.put(0x81422C, "Nutmeg");
        sNamedColorsMap.put(0x683600, "Nutmeg Wood Finish");
        sNamedColorsMap.put(0xFEEFCE, "Oasis");
        sNamedColorsMap.put(0x02866F, "Observatory");
        sNamedColorsMap.put(0x41AA78, "Ocean Green");
        sNamedColorsMap.put(0xCC7722, "Ochre");
        sNamedColorsMap.put(0xE6F8F3, "Off Green");
        sNamedColorsMap.put(0xFEF9E3, "Off Yellow");
        sNamedColorsMap.put(0x281E15, "Oil");
        sNamedColorsMap.put(0x901E1E, "Old Brick");
        sNamedColorsMap.put(0x724A2F, "Old Copper");
        sNamedColorsMap.put(0xCFB53B, "Old Gold");
        sNamedColorsMap.put(0xFDF5E6, "Old Lace");
        sNamedColorsMap.put(0x796878, "Old Lavender");
        sNamedColorsMap.put(0xC08081, "Old Rose");
        sNamedColorsMap.put(0x808000, "Olive");
        sNamedColorsMap.put(0x6B8E23, "Olive Drab");
        sNamedColorsMap.put(0xB5B35C, "Olive Green");
        sNamedColorsMap.put(0x8B8470, "Olive Haze");
        sNamedColorsMap.put(0x716E10, "Olivetone");
        sNamedColorsMap.put(0x9AB973, "Olivine");
        sNamedColorsMap.put(0xCDF4FF, "Onahau");
        sNamedColorsMap.put(0x2F270E, "Onion");
        sNamedColorsMap.put(0xA9C6C2, "Opal");
        sNamedColorsMap.put(0x8E6F70, "Opium");
        sNamedColorsMap.put(0x377475, "Oracle");
        sNamedColorsMap.put(0xFF681F, "Orange");
        sNamedColorsMap.put(0xFFA000, "Orange Peel");
        sNamedColorsMap.put(0xC45719, "Orange Roughy");
        sNamedColorsMap.put(0xFEFCED, "Orange White");
        sNamedColorsMap.put(0xDA70D6, "Orchid");
        sNamedColorsMap.put(0xFFFDF3, "Orchid White");
        sNamedColorsMap.put(0x9B4703, "Oregon");
        sNamedColorsMap.put(0x015E85, "Orient");
        sNamedColorsMap.put(0xC69191, "Oriental Pink");
        sNamedColorsMap.put(0xF3FBD4, "Orinoco");
        sNamedColorsMap.put(0x878D91, "Oslo Gray");
        sNamedColorsMap.put(0xE9F8ED, "Ottoman");
        sNamedColorsMap.put(0x2D383A, "Outer Space");
        sNamedColorsMap.put(0xFF6037, "Outrageous Orange");
        sNamedColorsMap.put(0x384555, "Oxford Blue");
        sNamedColorsMap.put(0x779E86, "Oxley");
        sNamedColorsMap.put(0xDAFAFF, "Oyster Bay");
        sNamedColorsMap.put(0xE9CECD, "Oyster Pink");
        sNamedColorsMap.put(0xA65529, "Paarl");
        sNamedColorsMap.put(0x776F61, "Pablo");
        sNamedColorsMap.put(0x009DC4, "Pacific Blue");
        sNamedColorsMap.put(0x778120, "Pacifika");
        sNamedColorsMap.put(0x411F10, "Paco");
        sNamedColorsMap.put(0xADE6C4, "Padua");
        sNamedColorsMap.put(0xFFFF99, "Pale Canary");
        sNamedColorsMap.put(0xC0D3B9, "Pale Leaf");
        sNamedColorsMap.put(0x988D77, "Pale Oyster");
        sNamedColorsMap.put(0xFDFEB8, "Pale Prim");
        sNamedColorsMap.put(0xFFE1F2, "Pale Rose");
        sNamedColorsMap.put(0x6E7783, "Pale Sky");
        sNamedColorsMap.put(0xC3BFC1, "Pale Slate");
        sNamedColorsMap.put(0x09230F, "Palm Green");
        sNamedColorsMap.put(0x19330E, "Palm Leaf");
        sNamedColorsMap.put(0xF4F2EE, "Pampas");
        sNamedColorsMap.put(0xEAF6EE, "Panache");
        sNamedColorsMap.put(0xEDCDAB, "Pancho");
        sNamedColorsMap.put(0xFFEFD5, "Papaya Whip");
        sNamedColorsMap.put(0x8D0226, "Paprika");
        sNamedColorsMap.put(0x317D82, "Paradiso");
        sNamedColorsMap.put(0xF1E9D2, "Parchment");
        sNamedColorsMap.put(0xFFF46E, "Paris Daisy");
        sNamedColorsMap.put(0x26056A, "Paris M");
        sNamedColorsMap.put(0xCADCD4, "Paris White");
        sNamedColorsMap.put(0x134F19, "Parsley");
        sNamedColorsMap.put(0x77DD77, "Pastel Green");
        sNamedColorsMap.put(0xFFD1DC, "Pastel Pink");
        sNamedColorsMap.put(0x639A8F, "Patina");
        sNamedColorsMap.put(0xDEF5FF, "Pattens Blue");
        sNamedColorsMap.put(0x260368, "Paua");
        sNamedColorsMap.put(0xD7C498, "Pavlova");
        sNamedColorsMap.put(0xFFE5B4, "Peach");
        sNamedColorsMap.put(0xFFF0DB, "Peach Cream");
        sNamedColorsMap.put(0xFFCC99, "Peach Orange");
        sNamedColorsMap.put(0xFFDCD6, "Peach Schnapps");
        sNamedColorsMap.put(0xFADFAD, "Peach Yellow");
        sNamedColorsMap.put(0x782F16, "Peanut");
        sNamedColorsMap.put(0xD1E231, "Pear");
        sNamedColorsMap.put(0xE8E0D5, "Pearl Bush");
        sNamedColorsMap.put(0xFCF4DC, "Pearl Lusta");
        sNamedColorsMap.put(0x716B56, "Peat");
        sNamedColorsMap.put(0x3EABBF, "Pelorous");
        sNamedColorsMap.put(0xE3F5E1, "Peppermint");
        sNamedColorsMap.put(0xA9BEF2, "Perano");
        sNamedColorsMap.put(0xD0BEF8, "Perfume");
        sNamedColorsMap.put(0xE1E6D6, "Periglacial Blue");
        sNamedColorsMap.put(0xCCCCFF, "Periwinkle");
        sNamedColorsMap.put(0xC3CDE6, "Periwinkle Gray");
        sNamedColorsMap.put(0x1C39BB, "Persian Blue");
        sNamedColorsMap.put(0x00A693, "Persian Green");
        sNamedColorsMap.put(0x32127A, "Persian Indigo");
        sNamedColorsMap.put(0xF77FBE, "Persian Pink");
        sNamedColorsMap.put(0x701C1C, "Persian Plum");
        sNamedColorsMap.put(0xCC3333, "Persian Red");
        sNamedColorsMap.put(0xFE28A2, "Persian Rose");
        sNamedColorsMap.put(0xFF6B53, "Persimmon");
        sNamedColorsMap.put(0x7F3A02, "Peru Tan");
        sNamedColorsMap.put(0x7C7631, "Pesto");
        sNamedColorsMap.put(0xDB9690, "Petite Orchid");
        sNamedColorsMap.put(0x96A8A1, "Pewter");
        sNamedColorsMap.put(0xA3807B, "Pharlap");
        sNamedColorsMap.put(0xFFF39D, "Picasso");
        sNamedColorsMap.put(0x6E4826, "Pickled Bean");
        sNamedColorsMap.put(0x314459, "Pickled Bluewood");
        sNamedColorsMap.put(0x45B1E8, "Picton Blue");
        sNamedColorsMap.put(0xFDD7E4, "Pig Pink");
        sNamedColorsMap.put(0xAFBDD9, "Pigeon Post");
        sNamedColorsMap.put(0x4B0082, "Pigment Indigo");
        sNamedColorsMap.put(0x6D5E54, "Pine Cone");
        sNamedColorsMap.put(0xC7CD90, "Pine Glade");
        sNamedColorsMap.put(0x01796F, "Pine Green");
        sNamedColorsMap.put(0x171F04, "Pine Tree");
        sNamedColorsMap.put(0xFFC0CB, "Pink");
        sNamedColorsMap.put(0xFF66FF, "Pink Flamingo");
        sNamedColorsMap.put(0xE1C0C8, "Pink Flare");
        sNamedColorsMap.put(0xFFDDF4, "Pink Lace");
        sNamedColorsMap.put(0xFFF1D8, "Pink Lady");
        sNamedColorsMap.put(0xFF91A4, "Pink Salmon");
        sNamedColorsMap.put(0xBEB5B7, "Pink Swan");
        sNamedColorsMap.put(0xC96323, "Piper");
        sNamedColorsMap.put(0xFEF4CC, "Pipi");
        sNamedColorsMap.put(0xFFE1DF, "Pippin");
        sNamedColorsMap.put(0xBA7F03, "Pirate Gold");
        sNamedColorsMap.put(0x9DC209, "Pistachio");
        sNamedColorsMap.put(0xC0D8B6, "Pixie Green");
        sNamedColorsMap.put(0xFF9000, "Pizazz");
        sNamedColorsMap.put(0xC99415, "Pizza");
        sNamedColorsMap.put(0x27504B, "Plantation");
        sNamedColorsMap.put(0x843179, "Plum");
        sNamedColorsMap.put(0x8F021C, "Pohutukawa");
        sNamedColorsMap.put(0xE5F9F6, "Polar");
        sNamedColorsMap.put(0x8DA8CC, "Polo Blue");
        sNamedColorsMap.put(0xF34723, "Pomegranate");
        sNamedColorsMap.put(0x660045, "Pompadour");
        sNamedColorsMap.put(0xEFF2F3, "Porcelain");
        sNamedColorsMap.put(0xEAAE69, "Porsche");
        sNamedColorsMap.put(0x251F4F, "Port Gore");
        sNamedColorsMap.put(0xFFFFB4, "Portafino");
        sNamedColorsMap.put(0x8B9FEE, "Portage");
        sNamedColorsMap.put(0xF9E663, "Portica");
        sNamedColorsMap.put(0xF5E7E2, "Pot Pourri");
        sNamedColorsMap.put(0x8C5738, "Potters Clay");
        sNamedColorsMap.put(0xBCC9C2, "Powder Ash");
        sNamedColorsMap.put(0xB0E0E6, "Powder Blue");
        sNamedColorsMap.put(0x9A3820, "Prairie Sand");
        sNamedColorsMap.put(0xD0C0E5, "Prelude");
        sNamedColorsMap.put(0xF0E2EC, "Prim");
        sNamedColorsMap.put(0xEDEA99, "Primrose");
        sNamedColorsMap.put(0xFEF5F1, "Provincial Pink");
        sNamedColorsMap.put(0x003153, "Prussian Blue");
        sNamedColorsMap.put(0xCC8899, "Puce");
        sNamedColorsMap.put(0x7D2C14, "Pueblo");
        sNamedColorsMap.put(0x3FC1AA, "Puerto Rico");
        sNamedColorsMap.put(0xC2CAC4, "Pumice");
        sNamedColorsMap.put(0xFF7518, "Pumpkin");
        sNamedColorsMap.put(0xB1610B, "Pumpkin Skin");
        sNamedColorsMap.put(0xDC4333, "Punch");
        sNamedColorsMap.put(0x4D3D14, "Punga");
        sNamedColorsMap.put(0x660099, "Purple");
        sNamedColorsMap.put(0x652DC1, "Purple Heart");
        sNamedColorsMap.put(0x9678B6, "Purple Mountain's Majesty");
        sNamedColorsMap.put(0xFF00CC, "Purple Pizzazz");
        sNamedColorsMap.put(0xE7CD8C, "Putty");
        sNamedColorsMap.put(0xFFFDF4, "Quarter Pearl Lusta");
        sNamedColorsMap.put(0xF7F2E1, "Quarter Spanish White");
        sNamedColorsMap.put(0xBD978E, "Quicksand");
        sNamedColorsMap.put(0xD6D6D1, "Quill Gray");
        sNamedColorsMap.put(0x623F2D, "Quincy");
        sNamedColorsMap.put(0x0C1911, "Racing Green");
        sNamedColorsMap.put(0xFF355E, "Radical Red");
        sNamedColorsMap.put(0xEADAB8, "Raffia");
        sNamedColorsMap.put(0xB9C8AC, "Rainee");
        sNamedColorsMap.put(0xF7B668, "Rajah");
        sNamedColorsMap.put(0x2E3222, "Rangitoto");
        sNamedColorsMap.put(0x1C1E13, "Rangoon Green");
        sNamedColorsMap.put(0x727B89, "Raven");
        sNamedColorsMap.put(0xD27D46, "Raw Sienna");
        sNamedColorsMap.put(0x734A12, "Raw Umber");
        sNamedColorsMap.put(0xFF33CC, "Razzle Dazzle Rose");
        sNamedColorsMap.put(0xE30B5C, "Razzmatazz");
        sNamedColorsMap.put(0x3C1206, "Rebel");
        sNamedColorsMap.put(0xFF0000, "Red");
        sNamedColorsMap.put(0x7B3801, "Red Beech");
        sNamedColorsMap.put(0x8E0000, "Red Berry");
        sNamedColorsMap.put(0xDA6A41, "Red Damask");
        sNamedColorsMap.put(0x860111, "Red Devil");
        sNamedColorsMap.put(0xFF3F34, "Red Orange");
        sNamedColorsMap.put(0x6E0902, "Red Oxide");
        sNamedColorsMap.put(0xED0A3F, "Red Ribbon");
        sNamedColorsMap.put(0x80341F, "Red Robin");
        sNamedColorsMap.put(0xD05F04, "Red Stage");
        sNamedColorsMap.put(0xC71585, "Red Violet");
        sNamedColorsMap.put(0x5D1E0F, "Redwood");
        sNamedColorsMap.put(0xC9FFA2, "Reef");
        sNamedColorsMap.put(0x9F821C, "Reef Gold");
        sNamedColorsMap.put(0x013F6A, "Regal Blue");
        sNamedColorsMap.put(0x86949F, "Regent Gray");
        sNamedColorsMap.put(0xAAD6E6, "Regent St Blue");
        sNamedColorsMap.put(0xFEEBF3, "Remy");
        sNamedColorsMap.put(0xA86515, "Reno Sand");
        sNamedColorsMap.put(0x002387, "Resolution Blue");
        sNamedColorsMap.put(0x2C1632, "Revolver");
        sNamedColorsMap.put(0x2E3F62, "Rhino");
        sNamedColorsMap.put(0xFFFEF0, "Rice Cake");
        sNamedColorsMap.put(0xEEFFE2, "Rice Flower");
        sNamedColorsMap.put(0xA85307, "Rich Gold");
        sNamedColorsMap.put(0xBBD009, "Rio Grande");
        sNamedColorsMap.put(0xF4D81C, "Ripe Lemon");
        sNamedColorsMap.put(0x410056, "Ripe Plum");
        sNamedColorsMap.put(0x8BE6D8, "Riptide");
        sNamedColorsMap.put(0x434C59, "River Bed");
        sNamedColorsMap.put(0xEAC674, "Rob Roy");
        sNamedColorsMap.put(0x00CCCC, "Robin's Egg Blue");
        sNamedColorsMap.put(0x4D3833, "Rock");
        sNamedColorsMap.put(0x9EB1CD, "Rock Blue");
        sNamedColorsMap.put(0xBA450C, "Rock Spray");
        sNamedColorsMap.put(0xC9B29B, "Rodeo Dust");
        sNamedColorsMap.put(0x747D83, "Rolling Stone");
        sNamedColorsMap.put(0xDE6360, "Roman");
        sNamedColorsMap.put(0x795D4C, "Roman Coffee");
        sNamedColorsMap.put(0xFFFEFD, "Romance");
        sNamedColorsMap.put(0xFFD2B7, "Romantic");
        sNamedColorsMap.put(0xECC54E, "Ronchi");
        sNamedColorsMap.put(0xA62F20, "Roof Terracotta");
        sNamedColorsMap.put(0x8E4D1E, "Rope");
        sNamedColorsMap.put(0xFF007F, "Rose");
        sNamedColorsMap.put(0xFBB2A3, "Rose Bud");
        sNamedColorsMap.put(0x800B47, "Rose Bud Cherry");
        sNamedColorsMap.put(0xE7BCB4, "Rose Fog");
        sNamedColorsMap.put(0xBF5500, "Rose of Sharon");
        sNamedColorsMap.put(0xFFF6F5, "Rose White");
        sNamedColorsMap.put(0x65000B, "Rosewood");
        sNamedColorsMap.put(0xC6A84B, "Roti");
        sNamedColorsMap.put(0xA23B6C, "Rouge");
        sNamedColorsMap.put(0x4169E1, "Royal Blue");
        sNamedColorsMap.put(0xAB3472, "Royal Heath");
        sNamedColorsMap.put(0x6B3FA0, "Royal Purple");
        sNamedColorsMap.put(0x796989, "Rum");
        sNamedColorsMap.put(0xF9F8E4, "Rum Swizzle");
        sNamedColorsMap.put(0x80461B, "Russet");
        sNamedColorsMap.put(0x755A57, "Russett");
        sNamedColorsMap.put(0xB7410E, "Rust");
        sNamedColorsMap.put(0x480404, "Rustic Red");
        sNamedColorsMap.put(0x86560A, "Rusty Nail");
        sNamedColorsMap.put(0x4C3024, "Saddle");
        sNamedColorsMap.put(0x583401, "Saddle Brown");
        sNamedColorsMap.put(0xF4C430, "Saffron");
        sNamedColorsMap.put(0xF9BF58, "Saffron Mango");
        sNamedColorsMap.put(0x9EA587, "Sage");
        sNamedColorsMap.put(0xB7A214, "Sahara");
        sNamedColorsMap.put(0xF1E788, "Sahara Sand");
        sNamedColorsMap.put(0xB8E0F9, "Sail");
        sNamedColorsMap.put(0x097F4B, "Salem");
        sNamedColorsMap.put(0xFF8C69, "Salmon");
        sNamedColorsMap.put(0xFEDB8D, "Salomie");
        sNamedColorsMap.put(0x685E6E, "Salt Box");
        sNamedColorsMap.put(0xF1F7F2, "Saltpan");
        sNamedColorsMap.put(0x3A2010, "Sambuca");
        sNamedColorsMap.put(0x0B6207, "San Felix");
        sNamedColorsMap.put(0x304B6A, "San Juan");
        sNamedColorsMap.put(0x456CAC, "San Marino");
        sNamedColorsMap.put(0x826F65, "Sand Dune");
        sNamedColorsMap.put(0xAA8D6F, "Sandal");
        sNamedColorsMap.put(0xAB917A, "Sandrift");
        sNamedColorsMap.put(0x796D62, "Sandstone");
        sNamedColorsMap.put(0xF5E7A2, "Sandwisp");
        sNamedColorsMap.put(0xFFEAC8, "Sandy Beach");
        sNamedColorsMap.put(0xF4A460, "Sandy brown");
        sNamedColorsMap.put(0x92000A, "Sangria");
        sNamedColorsMap.put(0x8D3D38, "Sanguine Brown");
        sNamedColorsMap.put(0xB16D52, "Santa Fe");
        sNamedColorsMap.put(0x9FA0B1, "Santas Gray");
        sNamedColorsMap.put(0xDED4A4, "Sapling");
        sNamedColorsMap.put(0x2F519E, "Sapphire");
        sNamedColorsMap.put(0x555B10, "Saratoga");
        sNamedColorsMap.put(0xE6E4D4, "Satin Linen");
        sNamedColorsMap.put(0xFFF5F3, "Sauvignon");
        sNamedColorsMap.put(0xFFF4E0, "Sazerac");
        sNamedColorsMap.put(0x675FA6, "Scampi");
        sNamedColorsMap.put(0xCFFAF4, "Scandal");
        sNamedColorsMap.put(0xFF2400, "Scarlet");
        sNamedColorsMap.put(0x431560, "Scarlet Gum");
        sNamedColorsMap.put(0x950015, "Scarlett");
        sNamedColorsMap.put(0x585562, "Scarpa Flow");
        sNamedColorsMap.put(0xA9B497, "Schist");
        sNamedColorsMap.put(0xFFD800, "School bus Yellow");
        sNamedColorsMap.put(0x8B847E, "Schooner");
        sNamedColorsMap.put(0x0066CC, "Science Blue");
        sNamedColorsMap.put(0x2EBFD4, "Scooter");
        sNamedColorsMap.put(0x695F62, "Scorpion");
        sNamedColorsMap.put(0xFFFBDC, "Scotch Mist");
        sNamedColorsMap.put(0x66FF66, "Screamin' Green");
        sNamedColorsMap.put(0xFBA129, "Sea Buckthorn");
        sNamedColorsMap.put(0x2E8B57, "Sea Green");
        sNamedColorsMap.put(0xC5DBCA, "Sea Mist");
        sNamedColorsMap.put(0x78A39C, "Sea Nymph");
        sNamedColorsMap.put(0xED989E, "Sea Pink");
        sNamedColorsMap.put(0x80CCEA, "Seagull");
        sNamedColorsMap.put(0x731E8F, "Seance");
        sNamedColorsMap.put(0xF1F1F1, "Seashell");
        sNamedColorsMap.put(0xFFF5EE, "Seashell Peach");
        sNamedColorsMap.put(0x1B2F11, "Seaweed");
        sNamedColorsMap.put(0xF0EEFD, "Selago");
        sNamedColorsMap.put(0xFFBA00, "Selective Yellow");
        sNamedColorsMap.put(0x704214, "Sepia");
        sNamedColorsMap.put(0x2B0202, "Sepia Black");
        sNamedColorsMap.put(0x9E5B40, "Sepia Skin");
        sNamedColorsMap.put(0xFFF4E8, "Serenade");
        sNamedColorsMap.put(0x837050, "Shadow");
        sNamedColorsMap.put(0x9AC2B8, "Shadow Green");
        sNamedColorsMap.put(0xAAA5A9, "Shady Lady");
        sNamedColorsMap.put(0x4EABD1, "Shakespeare");
        sNamedColorsMap.put(0xFBFFBA, "Shalimar");
        sNamedColorsMap.put(0x33CC99, "Shamrock");
        sNamedColorsMap.put(0x25272C, "Shark");
        sNamedColorsMap.put(0x004950, "Sherpa Blue");
        sNamedColorsMap.put(0x02402C, "Sherwood Green");
        sNamedColorsMap.put(0xE8B9B3, "Shilo");
        sNamedColorsMap.put(0x6B4E31, "Shingle Fawn");
        sNamedColorsMap.put(0x788BBA, "Ship Cove");
        sNamedColorsMap.put(0x3E3A44, "Ship Gray");
        sNamedColorsMap.put(0xB20931, "Shiraz");
        sNamedColorsMap.put(0xE292C0, "Shocking");
        sNamedColorsMap.put(0xFC0FC0, "Shocking Pink");
        sNamedColorsMap.put(0x5F6672, "Shuttle Gray");
        sNamedColorsMap.put(0x646A54, "Siam");
        sNamedColorsMap.put(0xF3E7BB, "Sidecar");
        sNamedColorsMap.put(0xBDB1A8, "Silk");
        sNamedColorsMap.put(0xC0C0C0, "Silver");
        sNamedColorsMap.put(0xACACAC, "Silver Chalice");
        sNamedColorsMap.put(0xC9C0BB, "Silver Rust");
        sNamedColorsMap.put(0xBFC1C2, "Silver Sand");
        sNamedColorsMap.put(0x66B58F, "Silver Tree");
        sNamedColorsMap.put(0x9FD7D3, "Sinbad");
        sNamedColorsMap.put(0x7A013A, "Siren");
        sNamedColorsMap.put(0x718080, "Sirocco");
        sNamedColorsMap.put(0xD3CBBA, "Sisal");
        sNamedColorsMap.put(0xCAE6DA, "Skeptic");
        sNamedColorsMap.put(0x76D7EA, "Sky Blue");
        sNamedColorsMap.put(0x708090, "Slate Gray");
        sNamedColorsMap.put(0x003399, "Smalt");
        sNamedColorsMap.put(0x51808F, "Smalt Blue");
        sNamedColorsMap.put(0x605B73, "Smoky");
        sNamedColorsMap.put(0xF7FAF7, "Snow Drift");
        sNamedColorsMap.put(0xE4FFD1, "Snow Flurry");
        sNamedColorsMap.put(0xD6FFDB, "Snowy Mint");
        sNamedColorsMap.put(0xE2D8ED, "Snuff");
        sNamedColorsMap.put(0xFFFBF9, "Soapstone");
        sNamedColorsMap.put(0xD1C6B4, "Soft Amber");
        sNamedColorsMap.put(0xF5EDEF, "Soft Peach");
        sNamedColorsMap.put(0x893843, "Solid Pink");
        sNamedColorsMap.put(0xFEF8E2, "Solitaire");
        sNamedColorsMap.put(0xEAF6FF, "Solitude");
        sNamedColorsMap.put(0xFD7C07, "Sorbus");
        sNamedColorsMap.put(0xCEB98F, "Sorrell Brown");
        sNamedColorsMap.put(0x6A6051, "Soya Bean");
        sNamedColorsMap.put(0x819885, "Spanish Green");
        sNamedColorsMap.put(0x2F5A57, "Spectra");
        sNamedColorsMap.put(0x6A442E, "Spice");
        sNamedColorsMap.put(0x885342, "Spicy Mix");
        sNamedColorsMap.put(0x74640D, "Spicy Mustard");
        sNamedColorsMap.put(0x816E71, "Spicy Pink");
        sNamedColorsMap.put(0xB6D1EA, "Spindle");
        sNamedColorsMap.put(0x79DEEC, "Spray");
        sNamedColorsMap.put(0x00FF7F, "Spring Green");
        sNamedColorsMap.put(0x578363, "Spring Leaves");
        sNamedColorsMap.put(0xACCBB1, "Spring Rain");
        sNamedColorsMap.put(0xF6FFDC, "Spring Sun");
        sNamedColorsMap.put(0xF8F6F1, "Spring Wood");
        sNamedColorsMap.put(0xC1D7B0, "Sprout");
        sNamedColorsMap.put(0xAAABB7, "Spun Pearl");
        sNamedColorsMap.put(0x8F8176, "Squirrel");
        sNamedColorsMap.put(0x2D569B, "St Tropaz");
        sNamedColorsMap.put(0x8A8F8A, "Stack");
        sNamedColorsMap.put(0x9F9F9C, "Star Dust");
        sNamedColorsMap.put(0xE5D7BD, "Stark White");
        sNamedColorsMap.put(0xECF245, "Starship");
        sNamedColorsMap.put(0x4682B4, "Steel Blue");
        sNamedColorsMap.put(0x262335, "Steel Gray");
        sNamedColorsMap.put(0x9C3336, "Stiletto");
        sNamedColorsMap.put(0x928573, "Stonewall");
        sNamedColorsMap.put(0x646463, "Storm Dust");
        sNamedColorsMap.put(0x717486, "Storm Gray");
        sNamedColorsMap.put(0x000741, "Stratos");
        sNamedColorsMap.put(0xD4BF8D, "Straw");
        sNamedColorsMap.put(0x956387, "Strikemaster");
        sNamedColorsMap.put(0x325D52, "Stromboli");
        sNamedColorsMap.put(0x714AB2, "Studio");
        sNamedColorsMap.put(0xBAC7C9, "Submarine");
        sNamedColorsMap.put(0xF9FFF6, "Sugar Cane");
        sNamedColorsMap.put(0xC1F07C, "Sulu");
        sNamedColorsMap.put(0x96BBAB, "Summer Green");
        sNamedColorsMap.put(0xFBAC13, "Sun");
        sNamedColorsMap.put(0xC9B35B, "Sundance");
        sNamedColorsMap.put(0xFFB1B3, "Sundown");
        sNamedColorsMap.put(0xE4D422, "Sunflower");
        sNamedColorsMap.put(0xE16865, "Sunglo");
        sNamedColorsMap.put(0xFFCC33, "Sunglow");
        sNamedColorsMap.put(0xFE4C40, "Sunset Orange");
        sNamedColorsMap.put(0xFF9E2C, "Sunshade");
        sNamedColorsMap.put(0xFFC901, "Supernova");
        sNamedColorsMap.put(0xBBD7C1, "Surf");
        sNamedColorsMap.put(0xCFE5D2, "Surf Crest");
        sNamedColorsMap.put(0x0C7A79, "Surfie Green");
        sNamedColorsMap.put(0x87AB39, "Sushi");
        sNamedColorsMap.put(0x888387, "Suva Gray");
        sNamedColorsMap.put(0x001B1C, "Swamp");
        sNamedColorsMap.put(0xACB78E, "Swamp Green");
        sNamedColorsMap.put(0xDCF0EA, "Swans Down");
        sNamedColorsMap.put(0xFBEA8C, "Sweet Corn");
        sNamedColorsMap.put(0xFD9FA2, "Sweet Pink");
        sNamedColorsMap.put(0xD3CDC5, "Swirl");
        sNamedColorsMap.put(0xDDD6D5, "Swiss Coffee");
        sNamedColorsMap.put(0x908D39, "Sycamore");
        sNamedColorsMap.put(0xA02712, "Tabasco");
        sNamedColorsMap.put(0xEDB381, "Tacao");
        sNamedColorsMap.put(0xD6C562, "Tacha");
        sNamedColorsMap.put(0xE97C07, "Tahiti Gold");
        sNamedColorsMap.put(0xEEF0C8, "Tahuna Sands");
        sNamedColorsMap.put(0xB32D29, "Tall Poppy");
        sNamedColorsMap.put(0xA8A589, "Tallow");
        sNamedColorsMap.put(0x991613, "Tamarillo");
        sNamedColorsMap.put(0x341515, "Tamarind");
        sNamedColorsMap.put(0xD2B48C, "Tan");
        sNamedColorsMap.put(0xFA9D5A, "Tan Hide");
        sNamedColorsMap.put(0xD9DCC1, "Tana");
        sNamedColorsMap.put(0x03163C, "Tangaroa");
        sNamedColorsMap.put(0xF28500, "Tangerine");
        sNamedColorsMap.put(0xED7A1C, "Tango");
        sNamedColorsMap.put(0x7B7874, "Tapa");
        sNamedColorsMap.put(0xB05E81, "Tapestry");
        sNamedColorsMap.put(0xE1F6E8, "Tara");
        sNamedColorsMap.put(0x073A50, "Tarawera");
        sNamedColorsMap.put(0xCFDCCF, "Tasman");
        sNamedColorsMap.put(0x483C32, "Taupe");
        sNamedColorsMap.put(0xB3AF95, "Taupe Gray");
        sNamedColorsMap.put(0x692545, "Tawny Port");
        sNamedColorsMap.put(0x1E433C, "Te Papa Green");
        sNamedColorsMap.put(0xC1BAB0, "Tea");
        sNamedColorsMap.put(0xD0F0C0, "Tea Green");
        sNamedColorsMap.put(0xB19461, "Teak");
        sNamedColorsMap.put(0x008080, "Teal");
        sNamedColorsMap.put(0x044259, "Teal Blue");
        sNamedColorsMap.put(0x3B000B, "Temptress");
        sNamedColorsMap.put(0xCD5700, "Tenn");
        sNamedColorsMap.put(0xFFE6C7, "Tequila");
        sNamedColorsMap.put(0xE2725B, "Terracotta");
        sNamedColorsMap.put(0xF8F99C, "Texas");
        sNamedColorsMap.put(0xFFB555, "Texas Rose");
        sNamedColorsMap.put(0xB69D98, "Thatch");
        sNamedColorsMap.put(0x403D19, "Thatch Green");
        sNamedColorsMap.put(0xD8BFD8, "Thistle");
        sNamedColorsMap.put(0xCCCAA8, "Thistle Green");
        sNamedColorsMap.put(0x33292F, "Thunder");
        sNamedColorsMap.put(0xC02B18, "Thunderbird");
        sNamedColorsMap.put(0xC1440E, "Tia Maria");
        sNamedColorsMap.put(0xC3D1D1, "Tiara");
        sNamedColorsMap.put(0x063537, "Tiber");
        sNamedColorsMap.put(0xFC80A5, "Tickle Me Pink");
        sNamedColorsMap.put(0xF1FFAD, "Tidal");
        sNamedColorsMap.put(0xBFB8B0, "Tide");
        sNamedColorsMap.put(0x16322C, "Timber Green");
        sNamedColorsMap.put(0xD9D6CF, "Timberwolf");
        sNamedColorsMap.put(0xF0EEFF, "Titan White");
        sNamedColorsMap.put(0x9A6E61, "Toast");
        sNamedColorsMap.put(0x715D47, "Tobacco Brown");
        sNamedColorsMap.put(0x3A0020, "Toledo");
        sNamedColorsMap.put(0x1B0245, "Tolopea");
        sNamedColorsMap.put(0x3F583B, "Tom Thumb");
        sNamedColorsMap.put(0xE79F8C, "Tonys Pink");
        sNamedColorsMap.put(0x7C778A, "Topaz");
        sNamedColorsMap.put(0xFD0E35, "Torch Red");
        sNamedColorsMap.put(0x0F2D9E, "Torea Bay");
        sNamedColorsMap.put(0x1450AA, "Tory Blue");
        sNamedColorsMap.put(0x8D3F3F, "Tosca");
        sNamedColorsMap.put(0x991B07, "Totem Pole");
        sNamedColorsMap.put(0xA9BDBF, "Tower Gray");
        sNamedColorsMap.put(0x5FB3AC, "Tradewind");
        sNamedColorsMap.put(0xE6FFFF, "Tranquil");
        sNamedColorsMap.put(0xFFFDE8, "Travertine");
        sNamedColorsMap.put(0xFC9C1D, "Tree Poppy");
        sNamedColorsMap.put(0x3B2820, "Treehouse");
        sNamedColorsMap.put(0x7C881A, "Trendy Green");
        sNamedColorsMap.put(0x8C6495, "Trendy Pink");
        sNamedColorsMap.put(0xE64E03, "Trinidad");
        sNamedColorsMap.put(0xC3DDF9, "Tropical Blue");
        sNamedColorsMap.put(0x00755E, "Tropical Rain Forest");
        sNamedColorsMap.put(0x4A4E5A, "Trout");
        sNamedColorsMap.put(0x8A73D6, "True V");
        sNamedColorsMap.put(0x363534, "Tuatara");
        sNamedColorsMap.put(0xFFDDCD, "Tuft Bush");
        sNamedColorsMap.put(0xEAB33B, "Tulip Tree");
        sNamedColorsMap.put(0xDEA681, "Tumbleweed");
        sNamedColorsMap.put(0x353542, "Tuna");
        sNamedColorsMap.put(0x4A4244, "Tundora");
        sNamedColorsMap.put(0xFAE600, "Turbo");
        sNamedColorsMap.put(0xB57281, "Turkish Rose");
        sNamedColorsMap.put(0xCABB48, "Turmeric");
        sNamedColorsMap.put(0x30D5C8, "Turquoise");
        sNamedColorsMap.put(0x6CDAE7, "Turquoise Blue");
        sNamedColorsMap.put(0x2A380B, "Turtle Green");
        sNamedColorsMap.put(0xBD5E2E, "Tuscany");
        sNamedColorsMap.put(0xEEF3C3, "Tusk");
        sNamedColorsMap.put(0xC5994B, "Tussock");
        sNamedColorsMap.put(0xFFF1F9, "Tutu");
        sNamedColorsMap.put(0xE4CFDE, "Twilight");
        sNamedColorsMap.put(0xEEFDFF, "Twilight Blue");
        sNamedColorsMap.put(0xC2955D, "Twine");
        sNamedColorsMap.put(0x66023C, "Tyrian Purple");
        sNamedColorsMap.put(0x120A8F, "Ultramarine");
        sNamedColorsMap.put(0xD84437, "Valencia");
        sNamedColorsMap.put(0x350E42, "Valentino");
        sNamedColorsMap.put(0x2B194F, "Valhalla");
        sNamedColorsMap.put(0x49170C, "Van Cleef");
        sNamedColorsMap.put(0xD1BEA8, "Vanilla");
        sNamedColorsMap.put(0xF3D9DF, "Vanilla Ice");
        sNamedColorsMap.put(0xFFF6DF, "Varden");
        sNamedColorsMap.put(0x72010F, "Venetian Red");
        sNamedColorsMap.put(0x055989, "Venice Blue");
        sNamedColorsMap.put(0x928590, "Venus");
        sNamedColorsMap.put(0x5D5E37, "Verdigris");
        sNamedColorsMap.put(0x495400, "Verdun Green");
        sNamedColorsMap.put(0xFF4D00, "Vermilion");
        sNamedColorsMap.put(0xB14A0B, "Vesuvius");
        sNamedColorsMap.put(0x534491, "Victoria");
        sNamedColorsMap.put(0x549019, "Vida Loca");
        sNamedColorsMap.put(0x64CCDB, "Viking");
        sNamedColorsMap.put(0x983D61, "Vin Rouge");
        sNamedColorsMap.put(0xCB8FA9, "Viola");
        sNamedColorsMap.put(0x290C5E, "Violent Violet");
        sNamedColorsMap.put(0x240A40, "Violet");
        sNamedColorsMap.put(0x991199, "Violet Eggplant");
        sNamedColorsMap.put(0xF7468A, "Violet Red");
        sNamedColorsMap.put(0x40826D, "Viridian");
        sNamedColorsMap.put(0x678975, "Viridian Green");
        sNamedColorsMap.put(0xFFEFA1, "Vis Vis");
        sNamedColorsMap.put(0x8FD6B4, "Vista Blue");
        sNamedColorsMap.put(0xFCF8F7, "Vista White");
        sNamedColorsMap.put(0xFF9980, "Vivid Tangerine");
        sNamedColorsMap.put(0x803790, "Vivid Violet");
        sNamedColorsMap.put(0x533455, "Voodoo");
        sNamedColorsMap.put(0x10121D, "Vulcan");
        sNamedColorsMap.put(0xDECBC6, "Wafer");
        sNamedColorsMap.put(0x5A6E9C, "Waikawa Gray");
        sNamedColorsMap.put(0x363C0D, "Waiouru");
        sNamedColorsMap.put(0x773F1A, "Walnut");
        sNamedColorsMap.put(0x788A25, "Wasabi");
        sNamedColorsMap.put(0xA1E9DE, "Water Leaf");
        sNamedColorsMap.put(0x056F57, "Watercourse");
        sNamedColorsMap.put(0x7B7C94, "Waterloo");
        sNamedColorsMap.put(0xDCD747, "Wattle");
        sNamedColorsMap.put(0xFFDDCF, "Watusi");
        sNamedColorsMap.put(0xFFC0A8, "Wax Flower");
        sNamedColorsMap.put(0xF7DBE6, "We Peep");
        sNamedColorsMap.put(0xFFA500, "Web Orange");
        sNamedColorsMap.put(0x4E7F9E, "Wedgewood");
        sNamedColorsMap.put(0xB43332, "Well Read");
        sNamedColorsMap.put(0x625119, "West Coast");
        sNamedColorsMap.put(0xFF910F, "West Side");
        sNamedColorsMap.put(0xDCD9D2, "Westar");
        sNamedColorsMap.put(0xF19BAB, "Wewak");
        sNamedColorsMap.put(0xF5DEB3, "Wheat");
        sNamedColorsMap.put(0xF3EDCF, "Wheatfield");
        sNamedColorsMap.put(0xD59A6F, "Whiskey");
        sNamedColorsMap.put(0xF7F5FA, "Whisper");
        sNamedColorsMap.put(0xFFFFFF, "White");
        sNamedColorsMap.put(0xDDF9F1, "White Ice");
        sNamedColorsMap.put(0xF8F7FC, "White Lilac");
        sNamedColorsMap.put(0xF8F0E8, "White Linen");
        sNamedColorsMap.put(0xFEF8FF, "White Pointer");
        sNamedColorsMap.put(0xEAE8D4, "White Rock");
        sNamedColorsMap.put(0x7A89B8, "Wild Blue Yonder");
        sNamedColorsMap.put(0xECE090, "Wild Rice");
        sNamedColorsMap.put(0xF4F4F4, "Wild Sand");
        sNamedColorsMap.put(0xFF3399, "Wild Strawberry");
        sNamedColorsMap.put(0xFD5B78, "Wild Watermelon");
        sNamedColorsMap.put(0xB9C46A, "Wild Willow");
        sNamedColorsMap.put(0x3A686C, "William");
        sNamedColorsMap.put(0xDFECDA, "Willow Brook");
        sNamedColorsMap.put(0x65745D, "Willow Grove");
        sNamedColorsMap.put(0x3C0878, "Windsor");
        sNamedColorsMap.put(0x591D35, "Wine Berry");
        sNamedColorsMap.put(0xD5D195, "Winter Hazel");
        sNamedColorsMap.put(0xFEF4F8, "Wisp Pink");
        sNamedColorsMap.put(0x9771B5, "Wisteria");
        sNamedColorsMap.put(0xA4A6D3, "Wistful");
        sNamedColorsMap.put(0xFFFC99, "Witch Haze");
        sNamedColorsMap.put(0x261105, "Wood Bark");
        sNamedColorsMap.put(0x4D5328, "Woodland");
        sNamedColorsMap.put(0x302A0F, "Woodrush");
        sNamedColorsMap.put(0x0C0D0F, "Woodsmoke");
        sNamedColorsMap.put(0x483131, "Woody Brown");
        sNamedColorsMap.put(0x738678, "Xanadu");
        sNamedColorsMap.put(0xFFFF00, "Yellow");
        sNamedColorsMap.put(0xC5E17A, "Yellow Green");
        sNamedColorsMap.put(0x716338, "Yellow Metal");
        sNamedColorsMap.put(0xFFAE42, "Yellow Orange");
        sNamedColorsMap.put(0xFEA904, "Yellow Sea");
        sNamedColorsMap.put(0xFFC3C0, "Your Pink");
        sNamedColorsMap.put(0x7B6608, "Yukon Gold");
        sNamedColorsMap.put(0xCEC291, "Yuma");
        sNamedColorsMap.put(0x685558, "Zambezi");
        sNamedColorsMap.put(0xDAECD6, "Zanah");
        sNamedColorsMap.put(0xE5841B, "Zest");
        sNamedColorsMap.put(0x292319, "Zeus");
        sNamedColorsMap.put(0xBFDBE2, "Ziggurat");
        sNamedColorsMap.put(0xEBC2AF, "Zinnwaldite");
        sNamedColorsMap.put(0xF4F8FF, "Zircon");
        sNamedColorsMap.put(0xE4D69B, "Zombie");
        sNamedColorsMap.put(0xA59B91, "Zorba");
        sNamedColorsMap.put(0x044022, "Zuccini");
        sNamedColorsMap.put(0xEDF6FF, "Zumthor");
    }

    /**
     * Returns the name of an integer color value.
     *
     * @param color An integer color value.
     * @return The color name, or null if the color has no name.
     */
    public static String get(Integer color) {
        return sNamedColorsMap.get(NO_ALPHA_MASK & color);
    }
}